refactor(stateless hamburger): stateless hamburger
fremtind/jokul pull request #1369
Opened 2020-09-22 08:54 UTC by eduardodir

affects: @fremtind/jkl-hamburger-react, @fremtind/portal

BREAKING CHANGE:
Now you need to handle the state of active from the outside

ISSUES CLOSED: #1164

## 📥 Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## ☑️ Submission checklist

-   [ ] I have read the [CONTRIBUTING](https://github.com/fremtind/jokul/blob/master/CONTRIBUTING.md) doc
-   [ ] `yarn build` works locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

## 💬 Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did, what alternatives you considered, etc...

2020-09-22 09:28 UTC, piofinn approved these changes
Nice! 😊

2020-09-22 09:28 UTC, piofinn commented on portal/src/components/Header/components/FullScreenMenu.tsx
> +                <CustomButton active={isActive} />
```suggestion
                <CustomButton active={isOpen} />
```

Begge deler funker, men `isOpen` er hakket riktigere 😊

2020-09-22 10:43 UTC, lfbergee commented on packages/hamburger-react/src/Hamburger.tsx
> +    onClick?: () => void;
Hvorfor er onClick optional?

2020-09-22 10:43 UTC, lfbergee commented on packages/hamburger-react/src/Hamburger.tsx
>  export const Hamburger = ({
Denne trenger nok forwardRef, for å kunne benytte seg av clickoutside funksjonalitet utenfor.

2020-09-22 10:44 UTC, lfbergee commented on packages/hamburger-react/src/Hamburger.tsx
> +    active = false,
Liker bedre `isSomething` over `something`, er hakket tydeligere syns jeg.

2020-09-22 10:46 UTC, lfbergee commented on packages/hamburger-react/src/Hamburger.test.tsx
> +        render(<Hamburger active />);
Kunne gjerne hatt motsatt test også, sjekke at den ikke settes om den ikke er der.

2020-09-22 10:46 UTC, lfbergee commented on packages/hamburger-react/src/Hamburger.test.tsx
> -    it("should render call onClick and set is active", () => {
Vil gjerne ha med denne testen fortsatt, at onClick fyres ved click når satt.

2020-09-22 10:47 UTC, lfbergee commented on packages/hamburger-react/documentation/Example.tsx
>      const divRef = React.useRef(null);
Denne kan fjernes nå

2020-09-22 10:49 UTC, lfbergee requested changes
Ser greit ut, men du må endre commit-meldingen, dette er breaking change, så commiten bør nok være noe ala
`feat(hamburger): BREAKING removes internal state`

2020-09-22 10:50 UTC, lfbergee commented
```
 packages/hamburger-react/src/Hamburger.test.tsx(8,17): error TS2741: Property 'active' is missing in type '{}' but required in type 'Props'.
packages/hamburger-react/src/Hamburger.test.tsx(12,17): error TS2741: Property 'active' is missing in type '{ negative: true; }' but required in type 'Props'.
packages/hamburger-react/src/Hamburger.test.tsx(26,17): error TS2741: Property 'active' is missing in type '{ description: string; }' but required in type 'Props'.
packages/hamburger-react/src/Hamburger.test.tsx(35,39): error TS2741: Property 'active' is missing in type '{}' but required in type 'Props'.
```

fra tsc kommandoen

2020-09-22 14:17 UTC, piofinn commented
> Ser greit ut, men du må endre commit-meldingen, dette er breaking change, så commiten bør nok være noe ala
> `feat(hamburger): BREAKING removes internal state`

Ser da ut som den er merket som breaking?

> affects: @fremtind/jkl-hamburger-react, @fremtind/portal
>
> BREAKING CHANGE:
> Now you need to handle the state of active from the outside

2020-09-23 07:32 UTC, lfbergee commented
> > Ser greit ut, men du må endre commit-meldingen, dette er breaking change, så commiten bør nok være noe ala
> > `feat(hamburger): BREAKING removes internal state`
> 
> Ser da ut som den er merket som breaking?
> 
> > affects: @fremtind/jkl-hamburger-react, @fremtind/portal
> > BREAKING CHANGE:
> > Now you need to handle the state of active from the outside
> 
> (alt over er med i commit-meldingen)

Du har rett, det holder det. Litt rart at en refactor er breaking, så mener kommentaren min står, men Breaking delen holder.

2020-09-23 14:40 UTC, piofinn commented
> Litt rart at en refactor er breaking

Det er jeg for så vidt enig i 😅 Hadde nok vært bedre med `feat`, men det vil i hvert fall bli riktig versjonsnummer.

2020-09-23 14:44 UTC, piofinn commented on packages/hamburger-react/src/Hamburger.tsx
>      negative?: boolean;
Kanskje vi kan benytte anledningen til å endre denne til å hete `inverted` nå som det uansett blir breaking change? Er fint om det er konsekvent i alle komponentene 😊

```suggestion
    inverted?: boolean;
```

2020-11-01 16:31 UTC, Mikaila94 commented on packages/hamburger-react/src/Hamburger.tsx
> +            className={`jkl-hamburger ${active ? "jkl-hamburger--is-active" : ""} ${
burde heller benytte classnames-syntaksen her

2021-01-22 10:45 UTC, gbrownlee commented
Lukkes fordi den er utdatert.

2021-01-22 10:45 UTC, closed without merging