Feat/data loader testautoid
fremtind/jokul pull request #1406
Opened 2020-09-30 09:38 UTC by joms

## 📥 Proposed changes

Etter forespørsel fra test teamet har jeg lagt på `data-testautoid` attributten på loader komponenten. Dette for å kunne ha litt mer standardiserte tester for de forskjellige løsningene våre.

## ☑️ Submission checklist

-   [X] I have read the [CONTRIBUTING](https://github.com/fremtind/jokul/blob/master/CONTRIBUTING.md) doc
-   [X] `yarn build` works locally with my changes
-   [X] I have added tests that prove my fix is effective or that my feature works
-   [X] I have added necessary documentation (if appropriate)

2020-09-30 10:21 UTC, lfbergee requested changes
rebase master please, og fjern comittene som ikke skal v're der.

2020-09-30 10:23 UTC, joms commented
Wait what wtf! tror jeg branchet ut fra feil branch 🤦

2020-09-30 10:35 UTC, lfbergee commented
Blir veldig ukomfortabel av dette, uten at jeg klarer å artikulere hvorfor jeg syns det er ukomfortabelt.

Tror kanskje den bør være en prop med default verdi. Ser ikke helt hvorfor det skal være en verdi i å se at det er en loader der, uten å ha mer kontekst til loaderen. Men med en prop så kan man hvertfall si noe om intensjonen, `bm-loader-fetch-config`. 

Tror kanskje problemet mitt er hvorfor er det loader dette kom som ønske på først? Loadere er jo veldig lite interessante. Er literally en placeholder for det som faktisk er interessant.

2020-09-30 10:35 UTC, lfbergee approved these changes
:unamused:

2020-10-01 06:44 UTC, joms commented
> Tror kanskje den bør være en prop med default verdi. Ser ikke helt hvorfor det skal være en verdi i å se at det er en loader der, uten å ha mer kontekst til loaderen. Men med en prop så kan man hvertfall si noe om intensjonen, `bm-loader-fetch-config`.

Ja, det virker fornuftig.

2020-10-01 07:11 UTC, lfbergee approved these changes

2020-10-01 07:54 UTC, merged