feat(flipper): add flipper component
fremtind/jokul pull request #1534
Opened 2020-10-30 07:21 UTC by lfbergee

## 📥 Proposed changes

feat(flipper): add flipper animation component

affects: @fremtind/jkl-flipper-react, @fremtind/jkl-flipper, @fremtind/portal

## ☑️ Submission checklist

-   [ ] I have read the [CONTRIBUTING](https://github.com/fremtind/jokul/blob/master/CONTRIBUTING.md) doc
-   [ ] `yarn build` works locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

## 💬 Further comments

2020-10-30 07:22 UTC, lfbergee commented
@Steinop ta kontakt, så kan jeg spinne opp en demo

2020-10-30 08:05 UTC, lfbergee commented
Kommer en justering på screenreader hånteringen, og gjøre showFirst til å gi mening

2020-10-30 14:55 UTC, Steinop commented
"Flipper" virker litt misvisende som navn i forhold til hva komponenten faktisk gjør - egentlig bytter den mellom to eller flere verdier men den bør ikke forveksles med toggle switch / Toggle bar.
Tenker at "content toggle animation" er mer dekkende (men veldig langt). Evt "value push-up" eller "value switch", "value transition", "shift mask" "toggle mask" eller noe i den duren. Ta det som et innspill 😅

2020-10-30 22:19 UTC, joms requested changes
Veldig kul komponent, som jeg ser masse potensiale for bruk rundt! Enig med @Steinop i at komponentnavnet kunne vært mer beskrivende. Får veldig delfin-vibber av det 🐬

2020-10-30 22:19 UTC, joms commented on packages/flipper-react/src/Flipper.tsx
> +    showFirst: boolean;
Føler navngivingen her kan bli litt uklar. Hva med primary/secondary, eller initial/secondary og en prop for `showSecondary`?

2020-11-02 06:40 UTC, lfbergee commented
> Tenker at "content toggle animation" er mer dekkende (men veldig langt). Evt "value push-up" eller "value switch", "value transition", "shift mask" "toggle mask" eller noe i den duren. Ta det som et innspill sweat_smile

Naming er dritvanskelig, tar i mot alle forslag!

Var innom ContentToggle, men ble ikke helt komfortabel med den. Lekte også med tanken om å prefixe reneanimasjonskomponenter, så AnimatedContentToggle, men igjen ruller ikke helt av tunga. PushMask? AnimatedPushUp?

[![](https://api.gh-polls.com/poll/01EP3TY03B9NVAV1K1V29GHFDT/AnimatedPushUp)](https://api.gh-polls.com/poll/01EP3TY03B9NVAV1K1V29GHFDT/AnimatedPushUp/vote)
[![](https://api.gh-polls.com/poll/01EP3TY03B9NVAV1K1V29GHFDT/PushUp)](https://api.gh-polls.com/poll/01EP3TY03B9NVAV1K1V29GHFDT/PushUp/vote)
[![](https://api.gh-polls.com/poll/01EP3TY03B9NVAV1K1V29GHFDT/PushMask)](https://api.gh-polls.com/poll/01EP3TY03B9NVAV1K1V29GHFDT/PushMask/vote)
[![](https://api.gh-polls.com/poll/01EP3TY03B9NVAV1K1V29GHFDT/ContentToggle)](https://api.gh-polls.com/poll/01EP3TY03B9NVAV1K1V29GHFDT/ContentToggle/vote)
[![](https://api.gh-polls.com/poll/01EP3TY03B9NVAV1K1V29GHFDT/AnimatedContentToggle)](https://api.gh-polls.com/poll/01EP3TY03B9NVAV1K1V29GHFDT/AnimatedContentToggle/vote)

2020-11-02 08:51 UTC, Steinop commented
Liker også prefix-ideen for å gruppere animerte komponenter men ser at navnet klinger bedre uten 🤔

2020-11-02 13:49 UTC, joms commented
Prefixing tilfører i hvert fall en mening og en verdi til navnet. Selv om det ikke ruller helt av tungen føler jeg at et meningsfullt og beskrivende navn er viktigst.

2020-11-03 12:28 UTC, lfbergee commented
Jeg har hørt på demokratiet. Noe annet som tilsier at jeg ikke kan merge @joms ?

2020-11-04 08:42 UTC, joms approved these changes

2020-11-04 08:44 UTC, merged