Endre linjehøyde til 28px (line-height-3) på compact/body
fremtind/jokul pull request #1567
Opened 2020-11-09 15:26 UTC by frisol97

## 📥 Proposed changes

I core er linjehøyden feil i forhold til figma. Den er line-height-2 (24px), men i figma er den line-height-3 (28px). Koblet til issue #1479 

## ☑️ Submission checklist

-   [ ] I have read the [CONTRIBUTING](https://github.com/fremtind/jokul/blob/master/CONTRIBUTING.md) doc
-   [ ] `yarn build` works locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

## 💬 Further comments

Har ikke testet.

2020-11-09 17:37 UTC, Murstam approved these changes

2020-11-10 07:03 UTC, lfbergee commented
Vi trenger en ordentlig commitmelding på denne. Vil kanskje si at denne er breaking? Er 4px breaking? Vet ikke helt :p

Ta også en titt på alt som feiler av Cypress-testene, denne PRen påvirker nok ganske langt uten for seg selv. Hvis det er forventa endringer, så må du slette screenshotene som skal oppdateres, så vil github actionen commite inn nye screenshots ved neste bygg.

2020-11-10 07:04 UTC, lfbergee requested changes
Se kommentaren min

2020-11-10 07:08 UTC, frisol97 commented
> Vi trenger en ordentlig commitmelding på denne. Vil kanskje si at denne er breaking? Er 4px breaking? Vet ikke helt :p
> 
> Ta også en titt på alt som feiler av Cypress-testene, denne PRen påvirker nok ganske langt uten for seg selv. Hvis det er forventa endringer, så må du slette screenshotene som skal oppdateres, så vil github actionen commite inn nye screenshots ved neste bygg.

Lurte på det samme, det kan jo være breaking for noen. Tar en titt på testene.

2020-11-10 07:28 UTC, lfbergee commented
btw, pass også på at denne vil påvirke mer eller mindre alle komponentene våre, vi har dessverre ikke 100% testdekning av visuelle regresjonstester, så basilcy må du nesten gå igjennom alle komponentene og se at de ser fornuftige ut... Sorry ass, ser ut som verdens enkleste fiks, og mulig det er det, men den har lange armer og mye som må sjekkes :(

2021-03-16 10:44 UTC, closed without merging