Doc(tone): Added "read more" section with links
fremtind/jokul pull request #1760
Opened 2021-01-21 12:20 UTC by AudunBerdal

## 📥 Proposed changes

Vi skriver at vi skal være mestere på klarspråk, så derfor tenker jeg det er nyttig å vise til flere ressurser der man kan lære seg å skrive i klarspråk. Jeg har lagt til dette som en "les mer" seksjon under skriverådene som også bygger på prinsippene for klarspråk. Her har jeg linker til Språkrådets side og nettsiden til PLAIN, en engelsk klarspråkside. Begge sidene har gode eksempler på bruk av klarspråk.

## ☑️ Submission checklist

-   [x] I have read the [CONTRIBUTING](https://github.com/fremtind/jokul/blob/master/CONTRIBUTING.md) doc
-   [ ] `yarn build` works locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

## 💬 Further comments

For åpne linkene i en ny fane, har jeg brukt html og en _blank tag i kombinasjon med Markdown. Er det mulig med vår implementasjon av Markdown?

2021-01-21 13:33 UTC, lfbergee commented
@all-contributors please add @AudunBerdal for code and documentation

2021-01-21 13:35 UTC, lfbergee commented on portal/src/texts/profile/tone.mdx
> +Stemmen vår bygger på prinsippene for klarspråk, som handler om korrekt, klar og brukertilpasset kommunikasjon. I tillegg til skriverådene vi har listet opp her, kan vi anbefale sidene til <a href="h
Syns ikke så mye om target blank. Ta med `rel=noopener noreferrer` eller bytt til markdown lenker uten target blank :)

2021-01-21 13:35 UTC, lfbergee requested changes
Ta med rel eller ta vekk target blank

2021-01-22 14:51 UTC, AudunBerdal commented
Skjønner! Har lagt det til nå, @lfbergee

2021-01-25 07:43 UTC, lfbergee approved these changes

2021-01-25 08:00 UTC, lfbergee commented
Accpeted in #1771 to be handled as an internal PR.

2021-01-25 08:00 UTC, closed without merging