style(@fremtind/jkl-description-list): margin-adjustments in Descript…
fremtind/jokul pull request #2136
Opened 2021-08-18 09:01 UTC by Mikaila94

…ion List component

affects: @fremtind/jkl-description-list

## 📥 Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## ☑️ Submission checklist

-   [ ] I have read the [CONTRIBUTING](https://github.com/fremtind/jokul/blob/master/CONTRIBUTING.md) doc
-   [ ] `yarn build` works locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

## 💬 Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did, what alternatives you considered, etc...

2021-08-19 06:59 UTC, piofinn approved these changes

2021-08-19 07:01 UTC, piofinn requested changes
Du må slette snapshot'ene fra integrasjonstesten også 😊

2021-08-19 08:07 UTC, kennidenni approved these changes

2021-08-19 10:12 UTC, merged

2021-08-23 10:25 UTC, henrikhermansen commented
Her tror jeg du har misforstått conventional commits. Dette er ikke en style-endring, [den typen er for code style](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type), ikke for styling.
Noen commit types blir ikke tatt med i Changelog. Jeg mistenker at style er en av dem, og det er i så fall dumt.

Selv om dette ikke er en bugfix, vill jeg nok gått for fix.