Blog/creating markers google maps
fremtind/jokul pull request #2442
Opened 2021-11-03 14:55 UTC by SercanSercan

## ☑️ Sjekkliste

-   [ ] Jeg har lest [CONTRIBUTING](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) og dokumentasjon det henvises til
-   [ ] Jeg har satt target branch til `main`, eller `external-contributions` dersom pull requesten kommer fra en fork
-   [ ] Jeg har kjørt `yarn build` og `yarn ci:test` og disse gir ingen feil
-   [ ] Jeg har lagt til tester som demonstrerer at feilen er rettet eller featuren fungerer
-   [ ] Jeg har skrevet relevant dokumentasjon

2021-11-04 09:04 UTC, wkillerud requested changes
Har noen små kommentarer, men det ser veldig bra ut 👍

2021-11-04 09:04 UTC, wkillerud commented on portal/src/texts/blog/creating-markers-google-maps.mdx
> +`google.maps.Marker` receives a JSON object where the options are almost limitless.
Vis gjerne en lenke til dokumentasjonen så leserne enkelt kan se options om de vil

```suggestion
`google.maps.Marker` receives a JSON object where the [options are almost limitless](https://developers.google.com/maps/documentation/javascript/reference/marker#MarkerOptions).
```

2021-11-04 11:45 UTC, SercanSercan commented
> Har noen små kommentarer, men det ser veldig bra ut 👍

Takk for alle forslag, @wkillerud! Du er en flink redaktør! :)

2021-11-05 07:44 UTC, wkillerud approved these changes

2021-11-05 07:44 UTC, merged