feat: expand-button
fremtind/jokul pull request #2603
Opened 2021-12-15 14:27 UTC by wkillerud

ISSUES CLOSED: #2533 

## ☑️ Sjekkliste

-   [x] Jeg har lest [CONTRIBUTING](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) og dokumentasjon det henvises til
-   [x] Jeg har satt target branch til `main`, eller `external-contributions` dersom pull requesten kommer fra en fork
-   [x] Jeg har kjørt `yarn build` og `yarn ci:test` og disse gir ingen feil
-   [ ] Jeg har lagt til tester som demonstrerer at feilen er rettet eller featuren fungerer
-   [x] Jeg har skrevet relevant dokumentasjon

2021-12-15 14:27 UTC, wkillerud commented
Kom gjerne med navneforslag 😅

2021-12-15 14:32 UTC, wkillerud commented
Skal få koordinert en Figma-branch også

2021-12-15 14:35 UTC, wkillerud commented on packages/expand-button-react/documentation/ExpandButton.mdx
> +`Expand`-komponenten håndterer alt dette, men den plasserer alltid innholdet som ekspanderes direkte under knappen. Om du trenger en annen layout må du bruke `ExpandButton` direkte, og sørge for å te
```suggestion
`ExpandSection`-komponenten håndterer alt dette, men den plasserer alltid innholdet som ekspanderes direkte under knappen. Om du trenger en annen layout må du bruke `ExpandButton` direkte, og sørge for å teste med skjermleser.
```

2021-12-15 14:35 UTC, wkillerud commented on packages/icons-react/src/index.ts
> +export type { IconVariant as IconVariant } from "./icons/types";
```suggestion
export type { IconProps, IconVariant as IconVariant } from "./icons/types";
```

2021-12-16 09:48 UTC, wkillerud commented
Feedback som feiler igjen... Tror jeg fjerner den testen.

2021-12-16 11:40 UTC, piofinn requested changes
Ser bra ut! Eneste jeg gjerne vil ha fikset er uthevingen i eksemplet.

Har også noen forslag du kan se om du vil gjøre noe med eller ikke 😊

2021-12-16 11:40 UTC, piofinn commented on packages/expand-button-react/src/ExpandButton.tsx
> +            {!srOnly && children}
Vet at dette blir riktig, men jeg er ikke så glad i ha gjensidig utelukkende effekter som separate blokker. Hva med å heller sette

```tsx
const ContentWrapper = srOnly ? ScreenReaderOnly : React.Fragment;
```

i toppen og så ha

```tsx
<ContentWrapper>{children}</ContentWrapper>
```

her? Synes i hvert fall at det blir hakket klarere, men funker å ha det som det er også 😊

2021-12-16 11:40 UTC, piofinn commented on packages/expand-button-react/src/ExpandButton.tsx
> +    srOnly?: boolean;
For meg høres `srOnly` litt ut som om hele knappen blir skjult selv om det kun er teksten som skjules. Kanskje man kan ha et litt mer klargjørende navn? Hva med bare `hideText`/`hideContent`?

2021-12-16 11:40 UTC, piofinn commented on packages/expand-button-react/src/ExpandSection.test.tsx
> +            </p>
```suggestion
            <p>
                Vi kunne kanskje brukt en Accordion, men vi har ikke <em>flere</em> ting vi vil strukturere på denne
                måten. Det ser litt rart ut med ett AccordionItem, så da bruker vi heller en ExpandButton
            </p>
```

Ser nå at dette er en test, men kan like så godt være semantisk riktig overalt 😅

2021-12-16 11:40 UTC, piofinn commented on packages/expand-button-react/documentation/ExpandSectionExample.tsx
> +                </p>
```suggestion
                <p className="jkl-portal-paragraph">
                    Vi kunne kanskje brukt en Accordion, men vi har ikke <em>flere</em> ting vi vil strukturere på denne
                    måten. Det ser litt rart ut med ett AccordionItem, så da bruker vi heller en ExpandButton
                </p>
```

2021-12-16 11:40 UTC, piofinn commented on packages/expand-button-react/documentation/ExpandSectionExample.tsx
> +        </p>
```suggestion
        <p className="jkl-portal-paragraph">
            Vi kunne kanskje brukt en Accordion, men vi har ikke <em>flere</em> ting vi vil strukturere på
            denne måten. Det ser litt rart ut med ett AccordionItem, så da bruker vi heller en ExpandButton
        </p>
```

2021-12-16 11:40 UTC, piofinn commented on packages/expand-button-react/src/ExpandSection.tsx
> +    const [elementRef] = useAnimatedHeight(expanded);
`useAnimatedHeight` har mulighet for callbacks ved åpning/lukking via et `options`-argument. Kanskje det kunne eksponeres i Props?

https://github.com/fremtind/jokul/blob/1f3321e1db17432a5f299b891644acb34602a42e/packages/react-hooks/src/animation.tsx#L8

2021-12-16 11:40 UTC, piofinn commented on packages/icons-react/src/icons/types.ts
> +export type IconVariant = "inherit" | "small" | "medium" | "large";
❤️

2021-12-16 13:30 UTC, piofinn submitted a review, later dismissed

2021-12-17 08:26 UTC, kennidenni commented
Vi har bruk for at pilen også kan peke oppover. Er det noe vi bør ha med i denne også?

2021-12-17 08:41 UTC, wkillerud commented
> Vi har bruk for at pilen også kan peke oppover. Er det noe vi bør ha med i denne også?

Som i at pilen peker oppover når innholdet er skjult, og nedover når innholdet blir vist? Har du et skjermbilde jeg kan se @kennidenni ?

2021-12-17 08:46 UTC, kennidenni commented
![image](https://user-images.githubusercontent.com/31621649/146515866-11849c91-8d7e-4844-9a95-4de869973151.png)
@wkillerud

2021-12-17 08:48 UTC, wkillerud commented
Aha, ekspanderende innhold fra footer. Da gir det kanskje mer mening at pila peker i retning av bevegelsen ja. Jeg kan legge inn en variant først som sist @kennidenni  👍

2021-12-17 09:38 UTC, espkva commented on packages/expand-button/expand-button.scss
> +        .jkl-expand-button__arrow {
Lurer på om dette er en indikasjon på at variantene på ikonene våre kanskje ikke stemmer med faktisk bruk?

2021-12-17 09:57 UTC, wkillerud commented on packages/expand-button/expand-button.scss
> +        .jkl-expand-button__arrow {
Mulig. Vi har en `inherit`-variant på ikonene som ikke er animerte, men fordi denne variabelen brukes i diverse utregninger så er det ikke like enkelt med den samme varianten der (som bare arver tekststørrelsen). Jeg tenker dette er en metode som er innafor. Klart, er sikkert nyttig med en sjekk på ikonstørrelsene vi har i `core`, men vi tar ikke den runden nå kjenner jeg 😄

2021-12-17 09:59 UTC, espkva submitted a review, later dismissed

2021-12-17 11:08 UTC, kennidenni approved these changes

2021-12-21 15:04 UTC, wkillerud commented
@onordbo og jeg diskuterte oss fram til at Body med fontvekt 700 er brukt såpass mange steder i Jøkul at det bør bli dokumentert. Legger til en egen klasse og lister den i tabellen under Profil.

2021-12-21 15:31 UTC, merged