Ny og forbedret bildekomponent
fremtind/jokul pull request #2702
Opened 2022-02-04 12:10 UTC by piofinn

- Kan vise lavoppløselig forhåndsvisning
- Velger riktig bilde ut fra størrelse og skjermoppløsning
- Fungerer bra med både fast og flytende størrelsesforhold

**BREAKING CHANGE**:
Nytt API

## 🎯 Sjekkliste

-   [x] Minstekrav til dokumentasjon er oppfyllt (sjekk [Contributing](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) om du er usikker)
-   [x] Testet [responsivitet](https://jokul.fremtind.no/komigang/mobil) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [x] Testdekningen er god nok (enhetstest, visuell regresjonstest)
-   [x] `yarn build` og `yarn ci:test` gir ingen feil

2022-02-04 12:34 UTC, piofinn commented
Denne er tenkt brukt i de nye kortene for å slippe gigantfiler, men tror den er mer generelt nyttig enn den gamle varianten!

2022-02-04 13:01 UTC, kennidenni commented on packages/image-react/documentation/image.mdx
> +Det er også mulig å sende inn kun ett enkelt bilde som kilde. I så fall lastes bildet inn på vanlig måte, iten forhåndsvisning.
```suggestion
Det er også mulig å sende inn kun ett enkelt bilde som kilde. I så fall lastes bildet inn på vanlig måte, uten forhåndsvisning.
```

2022-02-04 13:02 UTC, kennidenni approved these changes

2022-02-04 13:12 UTC, wkillerud requested changes
Jeg savner en `MIGRATION.md` med mer hjelp for meg som skal oppgradere enn "Nytt API" i changeloggen 😄

2022-02-04 13:12 UTC, wkillerud commented on packages/image-react/src/Image.tsx
> +     * Send inn en tom streng hvis bildet kun er dekorativt.
Kanskje og skrive et lite hint om at bilder [sannsynligvis ikke er dekorative](https://www.smashingmagazine.com/2021/06/img-alt-attribute-alternate-description-decorative/)

```suggestion
     * Send inn en tom streng hvis bildet kun er dekorativt. Sannsynligvis bør du beskrive innholdet i bildet så en person med nedsatt syn får en fullgod opplevelse av siden.
```

2022-02-04 13:12 UTC, wkillerud commented on packages/image-react/src/Image.tsx
> +    srcSet: string;
Funderer på om `srcSet` og `placeholder` bør være props på rotnivå. Jeg stusset litt over at `srcSet` var en underprop av `src` (og at `src.src` er en ting).

2022-02-04 13:12 UTC, wkillerud commented on packages/react-hooks/src/useImageLoadingStatus.ts
> +export const useImageLoadingStatus = (callback?: () => void): [RefObject<HTMLImageElement>, boolean] => {
Er denne kanskje såpass snever at den hører hjemme i `image`-pakka?

2022-02-04 15:21 UTC, piofinn commented on packages/image-react/src/Image.tsx
> +    srcSet: string;
Ja, APIet starta ut litt annerledes og det ga nok mer mening da. Enig med deg i at vi godt bare kan ha tre props slik det er kodet nå. Da slipper vi typeguard-funksjonen også.

2022-02-04 15:26 UTC, piofinn commented on packages/react-hooks/src/useImageLoadingStatus.ts
> +export const useImageLoadingStatus = (callback?: () => void): [RefObject<HTMLImageElement>, boolean] => {
Hehe, ja den er sikkert det. Ble bare litt revet med! 😄 Vi burde sikker også fjerne den gamle `useResponsiveImage`-hooken som ble brukt i den gamle komponenten. Evt. merke den som deprecated hvis vi ikke vil ha breaking change i `jkl-react-hooks`

2022-02-07 07:56 UTC, wkillerud submitted a review, later dismissed

2022-02-07 08:46 UTC, piofinn commented
Må få rebaset denne nå, men lurer også på om noen har noen gode tips til hvordan vi kan få bumpet denne til v1.0 på fornuftig måte? 😅 Hvis jeg endrer versjon manuelt til 1.0.0 blir det vel bumpet til 2.0.0 av Lerna fordi det står at det er en breaking change 😑

@wkillerud @joms eller andre?

2022-02-07 08:51 UTC, wkillerud commented
Har ikke funnet noen lur måte å gjøre det på @piofinn. Nye pakker har et liknende problem, der de gjerne blir publisert som `1.1.0` som første versjon. Tenker det ikke gjør noe om vi drar en Winamp og hopper over `1.x`.

2022-02-07 09:23 UTC, piofinn commented on packages/image-react/documentation/style.scss
> +.fluid {
```suggestion

.fluid {
```

2022-02-07 09:27 UTC, piofinn commented
> Tenker det ikke gjør noe om vi drar en Winamp og hopper over `1.x`.

"Så store forbedringer at vi går rett til v2!" 🙃

2022-02-07 09:51 UTC, wkillerud approved these changes

2022-02-07 10:44 UTC, merged