feat: added optional arrows to buttons
fremtind/jokul pull request #2775
Opened 2022-03-02 09:43 UTC by kennidenni

ISSUES CLOSED: #2772

Lagt til piler for knapper

## 🎯 Sjekkliste

-   [ ] Nye features er dokumentert (sjekk [Contributing](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) om du er usikker på hva som trengs av dokumentasjon)
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/komigang/mobil) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [ ] `yarn build` og `yarn ci:test` gir ingen feil

2022-03-02 12:58 UTC, kennidenni commented on packages/button-react/documentation/index.tsx
> +            choiceProps: [
Aha, skulle akkurat til å spør hvorfor det ikke kom opp i  preview, men det gir meining og skal fikse det! 

Hmm hvorfor fikk jeg ikke noe feil på snapshot når branchen testet?

2022-03-02 14:33 UTC, joms requested changes
Jeg ønsker meg pilene i kode-eksempelet også <3

2022-03-02 16:07 UTC, wkillerud approved these changes

2022-03-03 10:05 UTC, joms commented
> > Jeg ønsker meg pilene i kode-eksempelet også <3
> 
> Er de ikke der nå? 👀 Edit: hehe, hadde !== i stedet for ===

![image](https://user-images.githubusercontent.com/537060/156542527-8cbd85ba-47a0-4fbb-8b78-12d881615866.png)

Ikke helt 😅  arrow-propen burde ikke vises om pil ikke er valgt, og så oppdaterer den seg ikke ihht. valgt egenskap

2022-03-04 15:06 UTC, wkillerud approved these changes

2022-03-07 12:27 UTC, merged