docs: ny onboarding
fremtind/jokul pull request #2837
Opened 2022-04-21 13:06 UTC by wkillerud

- Nystrukturert onboarding
- Nytt punkt i toppmenyen: Guider. En del innhold fra tidligere Kom i gang flyttet hit.
- Lenk til ny onboarding fra forsiden, dokumentasjon rundt om på GitHub

## 🎯 Sjekkliste

-   [x] `yarn build` og `yarn ci:test` gir ingen feil

2022-04-21 14:54 UTC, gbrownlee requested changes

2022-04-21 14:54 UTC, gbrownlee commented on portal/src/texts/kom-i-gang/degOgJokul.mdx
> +Litt som et samvirkelag, er Jøkul et produkt av en større felles innsats fra alle som bruker systemet. Siden du er både brukeren og skaperen av Jøkul, blir designsystemet så bra som du gjør det til s
```suggestion
Litt som et samvirkelag, er Jøkul et produkt av en større felles innsats fra alle som bruker systemet. Siden du er både brukeren og skaperen av Jøkul, blir designsystemet så bra som du gjør det til selv ved at du deltar i utviklingen. Det betyr også at hvis du ser noe som er feil eller som kan forbedres, så er det opp til deg å gjennomføre den endringen.
```

2022-04-21 14:54 UTC, gbrownlee commented on portal/src/texts/kom-i-gang/degOgJokul.mdx
> +Når vi ikke er fysisk samlet deler vi idéer, forslag til nye funksjoner, endringer og bugs på GitHub. Ved å samle alt på ett sted gjør vi det enklere for alle å delta, og for kjerneteamet å holde ove
```suggestion
Når vi ikke er fysisk samlet, deler vi idéer, forslag til nye funksjoner, endringer og bugs på GitHub. Ved å samle alt på ett sted gjør vi det enklere for alle å delta og for kjerneteamet å holde oversikt. Innleggene stammer som regel fra behov og diskusjoner ute i teamene, eller forumet. GitHub er ofte startpunktet hvis du vil påvirke designsystemet.
```

2022-04-21 14:54 UTC, gbrownlee commented on portal/src/texts/kom-i-gang/degOgJokul.mdx
> +        description="Del dine idéer, eller diskuter Jøkul med andre designere og utviklere i Fremtind."
```suggestion
        description="Del dine idéer eller diskuter Jøkul med andre designere og utviklere i Fremtind."
```

2022-04-21 14:54 UTC, gbrownlee commented on portal/src/texts/kom-i-gang/degOgJokul.mdx
> +Vi samles ukentlig for å dele og drøfte hva som skjer i designsystemet. Forumet har ‘åpen mikk’ og hvem som helst kan stille opp med et tema de vil sparre med andre på, agendaen er basert på en [tråd
```suggestion
Vi samles ukentlig for å dele og drøfte hva som skjer i designsystemet. Forumet har ‘åpen mikk’ og hvem som helst kan stille opp med et tema de vil sparre med andre på. Agendaen er basert på en [tråd fra teams som kommer ut i forkant](https://teams.microsoft.com/l/channel/19%3adb7fc5da697547ad8a199247b3be66dc%40thread.skype/Support%2520Designsystem?groupId=460dde26-9370-4131-8b04-61b3e9b47048&tenantId=273051d7-ce03-4594-b66d-0c68e4c778c0). Ofte deler vi forumet i to med en presentasjonsdel først og en arbeidsdel hvor man kan sparre på tvers av team og fag.
```

2022-04-21 14:54 UTC, gbrownlee commented on portal/src/texts/kom-i-gang/hvaErJokul.mdx
> +Designsystemet vårt hjelper oss med å opprettholde en felles forståelse for hvordan vi gjør ting sammen. Det er mange gode grunner til å ha et designsystem, her i Fremtind gir det oss en god del ford
```suggestion
Designsystemet vårt hjelper oss med å opprettholde en felles forståelse for hvordan vi gjør ting sammen. Det er mange gode grunner til å ha et designsystem. I Fremtind gir det oss en god del fordeler, som for eksempel:
```

2022-04-21 14:54 UTC, gbrownlee commented on portal/src/texts/kom-i-gang/hvaErJokul.mdx
> +Jøkul har mange bevegelige deler, og det er mye man kan fordype seg i. På de neste sidene vil du få en kort innføring (cirka 15 minutter) i de viktigste temaene vi forventer at du kjenner til, så du
```suggestion
Jøkul har mange bevegelige deler og det er mye man kan fordype seg i. På de neste sidene vil du få en kort innføring (cirka 15 minutter) i de viktigste temaene vi forventer at du kjenner til, så du har gode forutsetninger for å bli en superbruker.
```

2022-04-21 14:54 UTC, gbrownlee commented on portal/src/texts/kom-i-gang/hvaErJokul.mdx
> +-   Hvordan er systemet satt sammen
```suggestion
-   Hvordan systemet er satt sammen
```

2022-04-21 14:54 UTC, gbrownlee commented on portal/src/texts/kom-i-gang/hvorKanJegFaHjelp.mdx
> +    description="Et system er summen av dets deler i samspill, ofte er det greit å ha en samlet oversikt over delene på ett sted."
```suggestion
    description="Et system er summen av dets deler i samspill. Ofte er det greit å ha en samlet oversikt over delene på ett sted."
```

2022-04-21 14:54 UTC, gbrownlee commented on portal/src/texts/kom-i-gang/praktiskDesign.mdx
> +Takket være masse flinke folk på internett så finnes det et trucklass med plugins, tips og triks for å gjøre Figma-hverdagen enklere, vi har samlet våre beste tips nedenfor:
```suggestion
Takket være masse flinke folk på internett så finnes det et trucklass med plugins, tips og triks for å gjøre Figma-hverdagen enklere. Vi har samlet våre beste tips nedenfor:
```

2022-04-21 15:55 UTC, onordbo commented on portal/src/texts/kom-i-gang/degOgJokul.mdx
> +    det før.
```suggestion
Med et designsystem følger det et litt annerledes tankesett som kan virke uvant dersom man ikke har et forhold til det fra før.
```

2022-04-22 14:21 UTC, wkillerud commented on portal/src/components/Typography/FormatProvider.tsx
>      return <Link {...props} />;
God idé! Legger den i backloggen inntil videre, men den vil nok kunne forenkle ting litt her og der, med litt clever intern bruk her i formatprovider.

2022-04-22 14:34 UTC, merged