feat(tooltip): add tooltip
fremtind/jokul pull request #3053
Opened 2022-09-06 06:38 UTC by daa1

## 🎯 Sjekkliste

-   [ ] Nye features er dokumentert (sjekk [Contributing](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) om du er usikker på hva som trengs av dokumentasjon)
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [ ] `yarn build` og `yarn ci:test` gir ingen feil

2022-09-06 07:22 UTC, wkillerud requested changes
Takk for at du løfter inn tooltipen i Jøkul! Dette ser veldig bra ut bortsett fra litt småpirk og noen "maler".

Savner litt innhold i React-komponentens README.

<details>
<summary>Forslag til innhold</summary>

```md
# [`@fremtind/jkl-tooltip-react`](https://jokul.fremtind.no/komponenter/tooltip)

Se portalen for [bruk og prinsipper](https://jokul.fremtind.no/komponenter/tooltip).

## Installasjon

**Tips:** [stilpakken](../tooltip/) blir automatisk installert som en avhengighet.

1. `yarn add @fremtind/jkl-tooltip-react` eller `npm i @fremtind/jkl-tooltip-react`.
2. Importér _både_ React-komponent og stilark i prosjektet ditt.

\```js
import { Tooltip } from "@fremtind/jkl-tooltip-react";

// Importer stilark via JavaScript med CSS-loader.
import "@fremtind/jkl-tooltip/tooltip.min.css";

// Lukkbar tooltip bruker IconButton internt, så du må også laste inn stilarket derfra.
import "@fremtind/jkl-icon-button/icon-button.min.css";
\```

\```scss
// Eller importer stilark via SCSS.
@use "@fremtind/jkl-tooltip/tooltip";
@use "@fremtind/jkl-icon-button/icon-button";
\```

```

</details>

Skulle også gjerne hatt en `tooltip-react/integration/tooltip.spec.js`.

<details>
<summary>Forslag til test</summary>

```js
/// <reference types="cypress" />
/// <reference types="../../../cypress/support" />

describe("Tooltip", () => {
    beforeEach(() => {
        cy.testComponent("tooltip");
    });

    it("renders correctly", () => {
        cy.takeSnapshots();
    });
});

```
</details>

2022-09-06 07:22 UTC, wkillerud commented on packages/tooltip-react/package.json
> +    "version": "0.0.1",
Vi gjør vanligvis første versjon av en pakke på denne måten, så blir første publiserte `1.0.0`.

```suggestion
    "version": "1.0.0-alpha.0",
```

2022-09-06 07:22 UTC, wkillerud commented on packages/tooltip/package.json
> +    "version": "0.0.1",
```suggestion
    "version": "1.0.0-alpha.0",
```

2022-09-06 07:22 UTC, wkillerud commented on packages/tooltip/package.json
> +        "dev": "echo \"Error: run dev from tag-react\" && exit 1"
```suggestion
        "dev": "echo \"Error: run dev from tooltip-react\" && exit 1"
```

2022-09-07 07:56 UTC, wkillerud submitted a review, later dismissed

2022-09-07 08:16 UTC, wkillerud commented
Venter med å merge til vi får Figma på plass. Har fått et lite vink om at det er noen endringsønsker på det visuelle.

2022-09-07 08:17 UTC, wkillerud reviewed
Venter med å merge til vi får Figma på plass. Har fått et lite vink om at det er noen endringsønsker på det visuelle.

2022-09-08 14:03 UTC, wkillerud commented
Sånn, da tror jeg at jeg skal være i mål. Ble noen runder til slutt der, men når Fremtind-bot pusher nye snapshots for regresjonstest så er denne klar til å merges fra min side.

2022-09-13 08:12 UTC, piofinn approved these changes

2022-09-27 11:33 UTC, wkillerud commented
Da er Figma-branch merget inn. Oppdaterte noen farger og paddinger, og justerte fokus-state.

2022-09-27 13:36 UTC, wkillerud commented
Da er eksempelet på https://jokul.fremtind.no/preview/tooltip/komponenter/tooltip oppdatert med nyeste design, hvis du vil ta en QA @Slaine2

2022-09-27 13:49 UTC, Slaine2 commented
@wkillerud 

- Hover mangler på Icon (sirkel).

- Det skal bare være Top, Top start, Top end, left og right brukbart.

- Jeg tror ikke vi trenger skriftstørrelser

2022-09-28 08:05 UTC, wkillerud submitted a review, later dismissed

2022-09-28 08:15 UTC, wkillerud approved these changes

2022-09-28 08:39 UTC, wkillerud commented
Merger denne nå så vi får pushet ut en v1. 

Har fikset tingene som er påpekt her og i issuet. Hvis det dukker opp bugs eller andre justeringsønsker får vi ta det underveis.

2022-09-28 08:40 UTC, merged