Feat/combobox
fremtind/jokul pull request #3414
Opened 2023-02-16 08:04 UTC by fremtindelise

## 🎯 Sjekkliste

-   [ ] Nye features er dokumentert (sjekk [Contributing](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) om du er usikker på hva som trengs av dokumentasjon)
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [ ] `pnpm build` og `pnpm ci:test` gir ingen feil

2023-02-17 08:26 UTC, wkillerud requested changes
Dette ser lovende ut, men er fortsatt noe som gjenstår før det kan merges.

TypeScript peker på noen typefeil som ser ut til å gå på blanding av `string` versus `string[]` versus `ValuePair[]`. Det er nok årsaken til at tags for valgte verdier bare er tomme kryss, og at kryss på en individuell tag ikke fjerner den.

`onChange` kalles med verdien for hvert enkelte valg, og er lik når noe legges til og fjernes. Som bruker av komponenten hadde jeg nok forventet å få tilgang til `selectedValue` med en liste av de valgte verdiene på en eller annen måte. , kanskje som et parameter nummer to til `onChange` (etter eventet). Se for eksempel hvordan `DatePicker` sin `onChange` fungerer.

- Tastaturnavigasjon med pil ned når fokuset står i inputfeltet flytter ikke fokuset til menyen slik som i søkbar Select og Autosuggest.
- Pil-ikonet flytter seg litt ned når den første tagen rendres inni inputboksen.
- Er noen småting som går på navngiving av CSS-klasser.
- Dokumentasjonen er litt uferdig.
- Savner et par automatiserte tester.

Vi kan godt se på dette sammen hvis du vil 👯

2023-02-17 08:32 UTC, fremtindelise commented
> 

Ja! Lagde denne PR'en i går så Øyvind kunne titte litt mtp. Figma. @piofinn og jeg begynte å se på en ting i går, så vi er i gang med å fikse ting og tang :-)

2023-03-20 12:32 UTC, wkillerud requested changes
Resolvet kommentarene fra forrige review som er løst, og la til to nye.

Jeg testet også med VoiceOver, og det er noen ting som må rettes (kanskje lettere å vise over Teams, men skriver ned her for å huske det selv 😄 ):

1. Om jeg har valgt én eller flere elementer, og så navigerer tilbake til comboboxen, så annonserer ikke skjermleseren at fokus er på knappen for å fjerne valget. Om jeg aktiverer knappen skjer ikke det jeg forventer. Med det som blir lest opp (minimert, knapp) ville jeg forventet at å trykke Control+Option+Space ekspanderte listen over elementer. I stedet fjerner jeg et valg.
2. Relatert, når jeg har fokus på Combobox med VoiceOver og trykker Control+Option+Space blir det første elementet i listen valgt, i stedet for at menyen åpnes (kanskje ikke en bug).
3. Når jeg bruker piltastene for å navigere i menyen blir ikke det fokuserte elementet lest opp. Jeg vet ikke hva jeg velger.
4. Når jeg filtrerer listen blir ikke det jeg skriver inn lest opp, slik som det gjør i inputfelt.
5. Når jeg velger et element flyttes fokuset tilbake til inputfeltet, men jeg får ikke beskjed om det. Ville forventet at skjermleseren annonserer at jeg står i et inputfelt.

En siste ting jeg la merke til (ikke noe UU-problem): når fokuset er i inputfeltet og jeg trykker på Pil ned, så flytter ikke fokus til lista med valg slik som det skjer i Select. Jeg ville forventet at de to komponentene oppførte seg likt, men her må jeg bruke Tab for å nå menyen.

2023-03-21 09:33 UTC, onordbo commented
Skulle vi kanskje gjort portal-eksempelet litt bredere, så det gjenspeiler problemet komponenten (originalt) var tiltenkt for å løse?

### Flyt-eksempel
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/4263132/226566185-689febb1-ef89-40c0-88f2-ca378223ff2c.png">

### Portal-eksempel
<img width="883" alt="image" src="https://user-images.githubusercontent.com/4263132/226566501-64f4b990-cb52-4ba4-938c-611dae76a840.png">


cc @ivnai @fremtindelise

2023-03-21 09:43 UTC, wkillerud commented
Jeg slang inn en prop for å gjøre selve eksempelboksen bredere også, @fremtindelise, for å få enda mer plass til eksempelet.

```
<ComponentExample
    scrollable={true}
    title="Table"
    component={TableExamples}
    knobs={tableExamplesProps}
    codeExample={tableExamplesCode}
    isWide // 👈
/>
```

2023-03-21 09:49 UTC, fremtindelise commented
> 

Ja, vi diskuterte så vidt det scenarioet du viser til, men på grunn av tid så avgrenset vi det til ICD-koder (som også var/er et reelt tilfelle). Med tanke på å skjemaer slik som på skjermbildet så foreslår jeg at vi kan bruke tagLabel til selve navnet på skjemaet. Ønsker man å korte ned innholdet i tag ytterligere, så kan man legge inn denne formateringen selv :) Kan man ha en hover-effekt som viser alt tekstinnhold, eventuelt at valgte elementer i nedtrekkslisten dukker opp i en liste-komponent under comboboxen?

2023-05-08 08:15 UTC, wkillerud approved these changes
Dette ser bra ut, godt jobba! 🙌 Det er en komplisert komponent, så vi kan sikkert pusse på den i det uendelige, men jeg synes dette er klart for å shippes. Så kan vi iterere på den når folk begynner å ta den i bruk.

:shipit:

2023-05-08 08:24 UTC, wkillerud approved these changes

2023-05-08 08:33 UTC, merged