Datepicker
fremtind/jokul pull request #3415
Opened 2023-02-16 08:34 UTC by maciejost

Closes https://github.com/fremtind/jokul/issues/3391

## 🎯 Sjekkliste

-   [ ] Nye features er dokumentert (sjekk [Contributing](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) om du er usikker på hva som trengs av dokumentasjon)
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [ ] `pnpm build` og `pnpm ci:test` gir ingen feil

2023-03-22 07:48 UTC, joms commented
Hele komponenten kræsjer om man skriver inn en dato manuelt 💣

2023-03-22 07:49 UTC, joms requested changes
Component goes kablamo 💣

2023-03-22 08:52 UTC, wkillerud requested changes
Som Jo Emil påpeker, komponenten eksploderer om man taster inn en dato manuelt. Jeg kom til `24.10.` uten problem, men på `24.10.1` sa det 💥

2023-03-22 08:52 UTC, wkillerud commented on packages/datepicker-react/src/internal/Calendar.tsx
> +            console.table({ year, offset, expectedDate: expectedDate.getFullYear() });
Logging bør fjernes

```suggestion
```

2023-03-22 08:52 UTC, wkillerud commented on packages/datepicker/_calendar-date-button.scss
> +    padding-top: jkl.$spacing-3xs; // adjust visual alignment of text
Når vi først er her, endre gjerne til tallbasert spacing.

2023-03-22 09:40 UTC, piofinn commented on packages/datepicker-react/src/DatePicker.test.tsx
> +describe.skip("Datepicker", () => {
Haha, oops 😅

2023-03-22 11:44 UTC, piofinn commented
Haha, denne PRen kommer aldri til å bli ferdig 🙃

<img width="418" alt="Skjermbilde 2023-03-22 kl  12 43 32" src="https://user-images.githubusercontent.com/25739615/226894020-b8fc50ec-d710-451a-8bec-c495089e9013.png">

2023-03-23 09:47 UTC, wkillerud submitted a review, later dismissed
Mulig `aria-label` for måned- og årvelger har godt av et `Gå til ...` eller `Velg ...`-prefix for å tydeliggjøre hva elementet styrer. Men dette ser veldig bra ut.

2023-03-23 12:01 UTC, wkillerud approved these changes

2023-03-23 12:12 UTC, merged