Fix/comboboxpadding
fremtind/jokul pull request #3534
Opened 2023-05-09 13:51 UTC by fremtindelise

## 🎯 Sjekkliste

-   [ ] Nye features er dokumentert (sjekk [Contributing](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) om du er usikker på hva som trengs av dokumentasjon)
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [ ] `pnpm build` og `pnpm ci:test` gir ingen feil

2023-05-10 06:10 UTC, wkillerud requested changes
Endringen løser bugen, men ønsker at navngiving av CSS-klasser følger kodestilen.

2023-05-10 06:10 UTC, wkillerud commented on packages/combobox/combobox.scss
> +    &__search-input.menu-closed {
Vi ønsker å holde oss til `BEM`-notasjon for klassenavn i Jøkul. At menyen er åpen eller lukket høres ut som en modifier på `.jkl-combobox` for meg. Så typ:

```scss
.jkl-combobox {
  // Annen CSS her

  &--menu-closed {
    .jkl-combobox__search-input {
      display: none;
    }
  }
}
```

og

```jsx
<InputGroup
  className={cn("jkl-combobox", className, {
      "jkl-combobox--invalid": !!errorLabel || invalid,
      "jkl-combobox--menu-closed": !showMenu && selectedValue.length >= 1,
  })}
```

2023-05-10 09:05 UTC, wkillerud submitted a review, later dismissed
Nice 😄 

Noe rart jeg la merke til på [branch previewen](https://jokul.fremtind.no/preview/fix/comboboxpadding/komponenter/combobox/), men som ikke skjer i prod:

- Velg en verdi så du får en tag i inputfeltet.
- Klikk på utsiden av menyen, så den lukker seg.
- Prøv å åpne menyen igjen.

Forstår ikke helt hva som skjer der. Endringen her er jo bare i CSS, og hvilke klassenavn som blir satt. Mulig det bare er en greie med forhåndsvisningen. Kanskje greit å dobbeltsjekke lokalt hos deg før merge.

2023-05-10 09:22 UTC, fremtindelise commented
> Nice 😄
> 
> Noe rart jeg la merke til på [branch previewen](https://jokul.fremtind.no/preview/fix/comboboxpadding/komponenter/combobox/), men som ikke skjer i prod:
> 
> * Velg en verdi så du får en tag i inputfeltet.
> * Klikk på utsiden av menyen, så den lukker seg.
> * Prøv å åpne menyen igjen.
> 
> Forstår ikke helt hva som skjer der. Endringen her er jo bare i CSS, og hvilke klassenavn som blir satt. Mulig det bare er en greie med forhåndsvisningen. Kanskje greit å dobbeltsjekke lokalt hos deg før merge.

Ah, ja, det er fordi inputfeltet blir borte når man har valgt en eller flere verdier og man lukker menyen. Jeg skal se på det :)

2023-05-10 12:49 UTC, wkillerud requested changes

2023-05-10 12:49 UTC, wkillerud commented on packages/combobox-react/src/Combobox.tsx
> +                    aria-hidden="true"
```suggestion
                    aria-hidden="true"
```

`aria-hidden` ødelegger for skjermleser (VoiceOver blir hvertfall ganske forvirret i Safari og Firefox), så den kan vi ikke ha her. Vi har ikke noe CSS som baserer seg på denne fra hva jeg kan se, så det skal gå fint.

2023-05-11 07:16 UTC, wkillerud approved these changes

2023-05-11 07:48 UTC, merged