feat: oppdater design på ToggleSwitch og legg til støtte for swipe
fremtind/jokul pull request #3536
Opened 2023-05-10 11:12 UTC by piofinn

Oppdaterer designet på ToggleSwitch og legger til støtte for swipe for toggle

ISSUES CLOSED: #3458

## 🎯 Sjekkliste

-   [x] Nye features er dokumentert (sjekk [Contributing](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) om du er usikker på hva som trengs av dokumentasjon)
-   [x] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [x] `pnpm build` og `pnpm ci:test` gir ingen feil

2023-05-10 11:13 UTC, piofinn commented on packages/toggle-switch-react/src/ToggleSwitch.test.tsx
> +            fireEvent(button, new MouseEvent("click", { bubbles: true, cancelable: true }));
Dette er litt uheldig, men jeg klarer virkelig ikke forstå hvorfor det ike fungerer. Har som sagt testet alle mulige kombinasjoner i flere nettlesere og iPhone-simulator, men Testing library nekter å klikke på knappen 🤷‍♂️

2023-05-10 11:45 UTC, piofinn commented
Er noen stiler som ikke snakker helt sammen her, så gjør om til draft så lenge.

2023-05-11 07:19 UTC, wkillerud commented on packages/toggle-switch-react/src/ToggleSwitch.test.tsx
> +            fireEvent(button, new MouseEvent("click", { bubbles: true, cancelable: true }));
Har du prøvd med `skipHover: true`? Husker det var noe trøbbel med Datepicker og Select (se `setup`-funksjonene der), som kan minne om dette.

2023-05-11 07:49 UTC, wkillerud requested changes

2023-05-11 07:49 UTC, wkillerud commented on packages/toggle-switch-react/integration/__image_snapshots__/ToggleSwitch renders correctly in high contrast #0.png
Denne varianten så ikke helt god ut med `forced-colors`. Er det en fokusring eller noe? Ser jo greit ut i neste skjermbilde.

2023-05-11 07:49 UTC, wkillerud commented on packages/toggle-switch-react/src/ToggleSwitch.tsx
> +    onSwipeLeft?: PointerEventHandler<HTMLButtonElement>;
Er det sånn at swiping ikke fungerer uten at disse lytterene er satt? I så fal synes jeg vi bør sette de som required, så vi ikke ender opp med at noen av togglene våre kan swipes, men ikke andre.

2023-05-11 07:49 UTC, wkillerud commented on packages/toggle-switch-react/src/ToggleSwitch.tsx
> +    pressed?: boolean;
Siden dette blir en breaking change uansett tenker jeg vi kan fjerne denne.

2023-05-11 07:49 UTC, wkillerud commented on packages/toggle-switch-react/src/ToggleSwitch.tsx
> +            <div className={cn("jkl-toggle-switch__wrapper", className)}>
Siden vi er her: wrapperen er ikke et element inni `jkl-toggle-switch`, så rename til `jkl-toggle-switch-wrapper`?

2023-05-11 07:49 UTC, wkillerud commented on packages/toggle-switch/toggle-switch.scss
> +    // TODO: Hvis vi fortsatt skal ha disabled state må den kanskje designes litt bedre
Er det tegnet noe? Hvis ikke tenker jeg vi kan fjerne den, samme som vi gjorde for kontekstuell meny.

2023-05-11 07:49 UTC, wkillerud commented on packages/toggle-switch/toggle-switch.scss
> -    --jkl-toggle-switch-focus-outline-color: #{jkl.$color-focus-color};
Disse endringene i CSS-variabler og klassenavn blir strengt talt en breaking change for CSSen.

2023-05-11 07:49 UTC, wkillerud commented on packages/toggle-switch-react/README.md
> +import "@fremtind/jkl-icons/icons.min.css";
Det at vi forventer mer CSS gjør at vi bør merke dette som en breaking change.

2023-05-11 07:49 UTC, wkillerud commented on packages/toggle-switch-react/src/useSwipeGesture.ts
> +                window.navigator.vibrate?.(200);
Som vi snakket om, kanskje drøye dette til vi har en dings å teste med, og kan tenke litt mer helhetlig på fysisk tilbakemelding i designsystemet.

2023-05-11 10:09 UTC, piofinn commented on packages/toggle-switch-react/integration/__image_snapshots__/ToggleSwitch renders correctly in high contrast #0.png
Jeg _tror_ det er fikset nå, men vi får se. Er litt vanskelig å teste lokalt 😅

2023-05-11 10:44 UTC, wkillerud approved these changes
Ser snapshoten må slettes for den forced-colors-fixen.

Et par forslag for noen smådetaljer, men dette ser bra ut! Nice å få sørget for konsekvent interaksjon på denne :)

2023-05-11 10:44 UTC, wkillerud commented on packages/toggle-switch-react/src/ToggleSwitch.tsx
> +    pressed: boolean,
Flip gjerne om på rekkefølgen her, så ligger eventhandleren nærmere de andre vi har. Event pleier komme først, etterfulgt av custom parametere.

2023-05-11 11:46 UTC, wkillerud reviewed
Veldig nice! :shipit:

2023-05-11 11:46 UTC, wkillerud approved these changes

2023-05-11 12:42 UTC, merged