Ny, modulær Tooltip-komponent
fremtind/jokul pull request #3582
Opened 2023-06-21 12:41 UTC by piofinn

Totaloverhaling av Tooltip-komponenten, som lar deg legge tooltip på egne interaktive elementer.

- 🛠️ Bygg opp egne tooltips med `<Tooltip>`, `<TooltipTrigger>` og `<TooltipContent>`
- ❓ Ferdigbygget komponent `<PopupTip>` for skjult tilleggsinformasjon med spørsmålstegnikon

## 🎯 Sjekkliste

-   [x] Nye features er dokumentert (sjekk [Contributing](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) om du er usikker på hva som trengs av dokumentasjon)
-   [x] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [x] `pnpm build` og `pnpm ci:test` gir ingen feil

2023-06-21 12:47 UTC, wkillerud requested changes
Vi trenger en migreringsdoc for breaking change

2023-06-21 13:07 UTC, wkillerud requested changes

2023-06-21 13:07 UTC, wkillerud commented on packages/tooltip-react/src/TooltipContent.tsx
> +            {triggerOn === "hover" && (
Er ikke dette relevant også ved klikk som trigger?

2023-06-22 07:41 UTC, piofinn commented on packages/tooltip-react/src/TooltipContent.tsx
> +            {triggerOn === "hover" && (
Ved klikk som trigger er teksten i tooltip resultatet av handlingen, så det blir litt rart om det leses opp av skjermleser før man klikker IMO. Ved hover beskriver teksten i tooltip handlingen, så der er den nødt til å leses opp før man trykker selv om den egentlig ikke er rendret ennå. Derav denne litt awkward span-en 😅 Ikke sikkert dette er en optimal løsning, men det oppleves i hvert fall ganske fornuftig med skjermlesere 😊

2023-06-23 08:58 UTC, piofinn commented on packages/tooltip-react/src/Tooltip.tsx
> +     * @default 0
Satte den til 250ms, som i eksemplet :) Så kan vi jo enkelt justere den senere.

2023-06-23 09:08 UTC, wkillerud requested changes

2023-06-23 09:08 UTC, wkillerud commented on packages/tooltip-react/integration/__image_snapshots__/PopupTip renders correctly #2.png
Denne har vokst ganske mye i bredden sammenlignet med forrige snapshot.

Ser at `max-width` ikke blir satt som forventet.

![image](https://github.com/fremtind/jokul/assets/1223410/7570e97e-6672-40f7-bec8-eafa9e1e61d3)

2023-06-23 09:26 UTC, piofinn commented on packages/tooltip-react/integration/__image_snapshots__/PopupTip renders correctly #2.png
Oi, good catch!

2023-06-23 11:37 UTC, piofinn commented on packages/tooltip-react/integration/__image_snapshots__/PopupTip renders correctly #2.png
@wkillerud `min()` liker visst ikke `*-content`-breddene som verdi. Fant noen bedre verdier å bruke, så nå blir det faktisk ivaretatt! Ser bedre ut også 😊

2023-06-23 11:44 UTC, wkillerud approved these changes

2023-06-23 13:12 UTC, wkillerud approved these changes

2023-07-03 10:46 UTC, wkillerud approved these changes

2023-07-03 11:00 UTC, merged