fix: handle inline elements in support labels
fremtind/jokul pull request #3893
Opened 2024-05-30 06:54 UTC by ivarni

SupportLabel uses flexbox to neatly display the text content next to the icon. This fix wraps the supplied label in a div to avoid having it participate in the parents flex layout

ISSUES CLOSED: #3892

## 🎯 Sjekkliste

-   [x] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [x] `pnpm build` og `pnpm ci:test` gir ingen feil

2024-06-06 08:42 UTC, piofinn requested changes

2024-06-06 08:42 UTC, piofinn commented on packages/input-group-react/src/SupportLabel.tsx
> +            <div>{errorLabel || helpLabel || label}</div>
Dette burde vel være en `span`? Skal kun være [phrasing content](https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories#phrasing_content) inne i `span`-elementer.

2024-06-07 04:30 UTC, ivarni commented on packages/input-group-react/src/SupportLabel.tsx
> +            <div>{errorLabel || helpLabel || label}</div>
Yes, fikser 👍🏽

2024-06-11 07:22 UTC, piofinn approved these changes

2024-06-11 07:28 UTC, merged