Legg til <UnorderedLinkList /> og <OrderedLinklist/>
fremtind/jokul pull request #3924
Opened 2024-08-07 08:15 UTC by kristianulv23

Legg til støtte for UnorderedLinkList og OrderedLinkList - [Github Issue](https://github.com/fremtind/jokul/issues/3920)

## 🎯 Sjekkliste

-   [x] Nye features er dokumentert (sjekk [Contributing](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) om du er usikker på hva som trengs av dokumentasjon)
-   [x] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [x] `pnpm build` og `pnpm ci:test` gir ingen feil

2024-08-07 09:33 UTC, ivarni commented on packages/list-react/src/OrderedLinkList.tsx
> +};
Denne burde sikkert ha `ComponentProps` som en "ol" og returnere et `<ol>` element?

2024-08-07 09:41 UTC, ivarni commented
![image](https://github.com/user-attachments/assets/f00dfdd3-d810-4774-a4f4-123d3edc931e)

Tror det er sånn som her på Fremtind.no også men jeg lurer på om det hadde sett nicere ut med ikonet vertikalt midtstilt?

2024-08-07 10:45 UTC, zenabii commented
Kan ikke alle disse linklist tsx filene slås sammen til én fil? 😄

2024-08-08 07:43 UTC, ivarni approved these changes

2024-08-13 04:34 UTC, ivarni approved these changes

2024-08-14 14:13 UTC, piofinn reviewed
Bra jobba! 🎉

Har et par forslag i dokumentasjonen, og ett angående klassenavn.

2024-08-14 14:13 UTC, piofinn commented on packages/list-react/documentation/List.mdx
> +Vi bruker link-lister for å presentere en liste med lenker. Dette kan være foreksempel være nyttig når du ønsker å lenke innad i en side eller til eksterne sider.
Hva med "Lenkelister"? Så er vi også konsekvente med "Nummererte/Unummererte lister" lenger opp. Så kan brødteksten være noe á la "Vi bruker komponenten `LinkList` for å presentere[…]"

2024-08-14 14:13 UTC, piofinn commented on packages/list-react/documentation/List.mdx
> +Vi bruker link-lister for å presentere en liste med lenker. Dette kan være foreksempel være nyttig når du ønsker å lenke innad i en side eller til eksterne sider.
Tror også det ble nevnt i issuet at vi burde trekke frem at det er god praksis å legge lenkelister i en `<nav>`-element med en tittel som sier noe om hva slags navigasjon det er. Kanskje det også kan få plass her før man går inn på de to variantene?

2024-08-16 14:28 UTC, piofinn approved these changes

2024-08-21 15:02 UTC, piofinn requested changes
Fant et par skriveleif i docsa, men det ser veldig bra ut ellers! 🚀

2024-08-28 06:43 UTC, ivarni approved these changes

2024-08-28 07:56 UTC, piofinn approved these changes

2024-08-28 11:29 UTC, piofinn approved these changes

2024-08-28 13:16 UTC, piofinn approved these changes

2024-08-28 13:22 UTC, merged

2024-08-29 10:39 UTC, Stormoen commented
Linklist eller listlink? Står begge deler, tenkte gjøre det likt i figma :)

![Skjermbilde 2024-08-29 kl  12 36 15](https://github.com/user-attachments/assets/c1264bf3-f9bf-4015-8a09-72fcce149680)