feat: rename alert to system
fremtind/jokul pull request #4012
Opened 2024-08-29 12:02 UTC by zenabii

BREAKING CHANGE:
alert message is renamed to system message

ISSUES CLOSED: #3978

## 🎯 Sjekkliste

-   [x] Nye features er dokumentert (sjekk [Contributing](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) om du er usikker på hva som trengs av dokumentasjon)
-   [x] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [x] `pnpm build` og `pnpm ci:test` gir ingen feil

2024-08-30 10:18 UTC, piofinn requested changes
Jeg tror vi må kjøre dette som en todelt endring, akkurat som med fjerningen av `Hamburger` og `ContentToggle`. Det vi egentlig gjør her er jo å _fjerne_ `alert-message`- og `alert-message-react`-pakkene og legge til to nye pakker. Foreslår altså at vi

1. lager en release som merker `alert-message` og `alert-message-react` som deprecated.
2. drar inn endringene i denne PRen, men som versjon 1.0.0 av hhv `system-message` og `system-message-react`.

Jeg legger inn noen forslag til endringer for steg 2 her som en review 😊

2024-08-30 10:18 UTC, piofinn commented on packages/system-message-react/CHANGELOG.md
Hele denne fila bør slettes. Det vil automatisk genereres en ny ved publisering.

2024-08-30 10:18 UTC, piofinn commented on packages/system-message-react/integration/alert-message.spec.js
Husk å gi nytt navn til denne filen 😊 Mappen med skjermbilder kan også slettes, siden det uansett vil genereres nye filer med det nye navnet på komponenten.

2024-08-30 10:18 UTC, piofinn commented on packages/system-message-react/package.json
>      "version": "11.1.19",
```suggestion
    "name": "@fremtind/jkl-system-message-react",
    "version": "1.0.0-alpha.0",
```
Denne vil automatisk oppdateres til `1.0.0` ved publisering

2024-08-30 10:18 UTC, piofinn commented on packages/system-message-react/package.json
> +        "@fremtind/jkl-system-message": "^9.0.12",
```suggestion
        "@fremtind/jkl-system-message": "^1.0.0-alpha.0",
```
Siden vi endrer versjonsnummer på stil pakken også. Denne vil også automatisk bli oppdatert.

2024-08-30 10:18 UTC, piofinn commented on packages/system-message/CHANGELOG.md
Som i React-pakka kan hele denne slettes for å bli generert på nytt.

2024-08-30 10:18 UTC, piofinn commented on packages/system-message/package.json
>      "version": "9.0.12",
```suggestion
    "name": "@fremtind/jkl-system-message",
    "version": "1.0.0-alpha.0",
```

2024-08-30 10:18 UTC, piofinn commented on portal/package.json
> +        "@fremtind/jkl-system-message-react": "^11.1.19",
```suggestion
        "@fremtind/jkl-system-message-react": "^1.0.0-alpha.0",
```

2024-08-30 10:18 UTC, piofinn commented on utils/package.json
> +        "@fremtind/jkl-system-message-react": "^11.1.18",
```suggestion
        "@fremtind/jkl-system-message-react": "^1.0.0-alpha.0",
```

2024-09-04 09:18 UTC, piofinn commented
Ser ut som ikke alle filene i Alert Message-pakkene er slettet her. Tipper det er der konfliktene kommer fra

2024-09-05 07:00 UTC, piofinn commented on packages/system-message-react/src/SystemMessage.tsx
> +SuccessSystemMessage.displayName = "SuccessSystemMessage";
Lurte på om vi skulle benytte sjansen, nå som vi uansett lager breaking change, til å endre fra separate komponenter til varianter? Altså `<SystemMessage variant="info" />` e.l.?

2024-09-05 09:23 UTC, piofinn approved these changes

2024-09-05 09:48 UTC, ivarni submitted a review, later dismissed

2024-09-05 14:10 UTC, ivarni approved these changes

2024-09-05 14:21 UTC, merged