Popover komponent
fremtind/jokul pull request #4088
Opened 2024-09-11 09:33 UTC by kristianulv23

Implementert en gjenbrukbar Popover-komponent

## 🎯 Sjekkliste

-   [ ] Nye features er dokumentert (sjekk [Contributing](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) om du er usikker på hva som trengs av dokumentasjon)
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [x] `pnpm build` og `pnpm ci:test` gir ingen feil

2024-09-11 19:15 UTC, piofinn reviewed
Ser veldig bra ut! 🎉

La inn et par kommentarer om definisjon av typer (som vi snakket om tidligere), og vil også gjerne at vi fjerner eller bytter ut `lodash` siden det tar ganske stor plass.

2024-09-11 19:15 UTC, piofinn commented on packages/popover-react/src/Popover.tsx
> +import { Props as ClickOptions } from "@floating-ui/react/src/hooks/useClick";
For disse som henter fra hooks kan du bruke `Parameters` som er innebygget i TypeScript:

```suggestion
type ClickOptions = Parameters<typeof useClick>[0];
```

Bruker `[1]` her fordi innstillingene blir sendt inn som andre argument til funksjonen i form av et objekt, som er det vi er ute etter.

2024-09-12 08:10 UTC, piofinn requested changes

2024-09-12 08:16 UTC, ivarni commented on packages/popover-react/src/Popover.tsx
> +import { merge } from "lodash";
Mener lodash støtter tree-shaking og også import via `lodash/merge`.

Mener her merger vi vel ikke ting som trenger å behandles rekursivt så kanskje `Object.assign` gjør jobben helt fint?

2024-09-12 10:54 UTC, kristianulv23 commented on packages/popover-react/src/Popover.tsx
> +import { merge } from "lodash";
Bruker merge da den dekker behover for deep merge. `Object.assign` og spread spread fungerer vel bare for shallow merging?

lodash har vel støtte for tree-shaking, ja. Men jeg kan undersøke `es-toolkit` om det er et bedre alternativ.

2024-09-12 11:07 UTC, ivarni commented on packages/popover-react/src/Popover.tsx
> +import { merge } from "lodash";
Jeg syns ikke det så ut fra typen til objektet som merges som at det var nødvendig med deep merge men da blingsa jeg sikkert

2024-09-13 07:28 UTC, kristianulv23 commented on packages/popover-react/src/Popover.tsx
> +import { merge } from "lodash";
JLa merke til at spread-operatoren ikke erstatter verdien brukeren ønsker å overstyre, men legger til et nytt objekt av samme type som overstyrer defaulten.

`[
    {
        "name": "offset",
        "options": 4
    },
    {
        "name": "flip",
        "options": {
            "padding": 5,
            "fallbackPlacements": [
                "bottom",
                "top"
            ]
        }
    },
    {
        "name": "shift",
        "options": {
            "padding": 12
        }
    },
    {
        "name": "offset",
        "options": 10
    }
]` 

Kanskje ikke et problem?

2024-09-13 11:12 UTC, ivarni commented on packages/popover-react/src/Popover.tsx
> +import { merge } from "lodash";
Sjekket ut branchen nå og forstår mer av hvordan strukturen ser ut.

Det kommer ann på hva APIet man ønsker å tilby er. Skal konsumenten kunne _legge til_ flere middlewares eller selv definere alle middlewares?. 

Her vil lodash/merge uansett neppe gjøre det vi vil. Den vil merge de to arrayene som om de var objekter og dermed erstatte defaultene med det som finnes i samme indeks i arrayet som kommer fra props.

Det vil si at med defaults
```
          middleware: [
                offset(_offset),
                flip({ padding: 5, fallbackPlacements: ["bottom", "top"] }),
                shift({ padding: 12 }),
            ]
```

og et props objekt som inneholder et middleware array med 1 element så vil `merge` erstatte `offset(_offset)` middlewaren med det som sendes inn og beholde de to andre siden merge vil slå sammen arrayene som helt vanlige objekter så vidt jeg kan se. 

Hvis man spreader array inn i hverandre i stedet vil man få `offset(_offset)` middlewaren to ganger. Det er muligens heller ikke det vi vil her men det er nok nærmere.

Hvis vi ønsker at brukeren erstatter _alle_ middlewares så tipper jeg vi vil ha
```
{
            open,
            placement: "bottom-start",
            strategy: "absolute",
            middleware: [
                offset(_offset),
                flip({ padding: 5, fallbackPlacements: ["bottom", "top"] }),
                shift({ padding: 12 }),
            ],
            whileElementsMounted: autoUpdate,
            onOpenChange,
            ..._floatingOptions,
        }
```

Hvis vi ønsker at brukeren erstatter middlewares med sammenfallende navn så tipper jeg vi vil ha
```
        const defaults: Middleware[] = [
            offset(_offset),
            flip({ padding: 5, fallbackPlacements: ["bottom", "top"] }),
            shift({ padding: 12 }),
        ]
        
        {
            open,
            placement: "bottom-start",
            strategy: "absolute",
            whileElementsMounted: autoUpdate,
            onOpenChange,
            middleware: [
                ...defaults
                    .map((m) => {
                        const override = _floatingOptions?.middleware?.find((_m) => {
                            return !!_m && _m.name === m.name;
                        });
                        return override || m;
                    })
                    .concat(
                        (_floatingOptions?.middleware?.filter((_m) => {
                            return !!_m && !defaults.some((__m) => __m.name === _m.name);
                        }) as Middleware[]) || [],
                    ),
            ],
        }
 ```
 
 Jeg tror egentlig det første er et bedre API. Dersom de som skal bruke komponenten ønsker kontroll over middleware så erstatter vi alle sammen med det som sendes inn. Ellers har de ingen måte å fjerne middlewares de ikke vil ha.

2024-09-13 12:28 UTC, piofinn commented on packages/popover-react/src/Popover.tsx
> +import { merge } from "lodash";
Ja, jeg lurer på om det er bedre å eksponere bare de relevante valgene i `useFloating`. Det er fint å ha valgene for de forskjellige typene interaksjoner, men er kanskje litt for åpent å eksponere hele APIet for hoved-hooken? Tipper det holder å eksponere `open`, `onOpenChange` og `placement`.

2024-09-13 19:14 UTC, kristianulv23 commented on packages/popover-react/src/Popover.tsx
> +import { merge } from "lodash";
Enig i at det er bedre å i første omgang begrense eksponeringen til kun de relevante valgene.

2024-09-16 10:31 UTC, piofinn approved these changes

2024-09-17 07:35 UTC, merged