fix(file-input): sync kode med figma design
fremtind/jokul pull request #4112
Opened 2024-09-23 10:48 UTC by kristianulv23

## 🎯 Sjekkliste

-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [x] `pnpm build` og `pnpm ci:test` gir ingen feil

2024-09-23 11:28 UTC, ivarni approved these changes

2024-09-23 12:16 UTC, piofinn commented on packages/file-input/_file.scss
> +    }
Jeg har begynt å angre litt på at jeg merket den "gamle" måten å angi disse på som deprecated 😅 Her vil du nok få en feil (strengt tatt en advarsel) fra Sass-compileren, siden disse mixin-ene lager nøstede deklarasjoner, og du har flere vanlige deklarasjoner på linjene under (se issue #4006).

Dette vil funke hvis du flytter disse linjene til under linje 48, men det gir jo egentlig mer mening å definere variabler i toppen av komponenten. Opp til deg om du vil flytte disse linjene eller gå tilbake til "deprecated"-varianten 😊

2024-09-23 12:32 UTC, piofinn requested changes
Dette ser veldig bra ut! Har lyst til å få ryddet litt opp i fargevariabler når vi først er inne og endrer på ting her, da får vi det også enda mer i synk med skissene 😊

2024-09-23 12:32 UTC, piofinn commented on packages/file-input/_file.scss
> +            background-color: var(--jkl-error);
Merker at vi må prioritere punktet om dokumentasjon av variabler 😅 Er ikke så lett å finne frem i jungelen nå.

```suggestion
            background-color: var(--jkl-color-background-alert-error);
```

2024-09-23 12:32 UTC, piofinn commented on packages/file-input/_file.scss
> +            background-color: var(--jkl-warning);
```suggestion
            background-color: var(--jkl-color-background-alert-warning);
```

2024-09-23 12:32 UTC, piofinn commented on packages/file-input/_file.scss
> +            color: jkl.$color-granitt;
Her kan du bruke `var(--jkl-color-text-on-alert)` for å få en farge som passer i både dark og light mode 😊

Jeg tror generelt det er en god idé å få gjort om fargevariablene fra øverst i fila til bruk av de semantiske fargevariablene våre. Kan godt se på det sammen hvis du vil!

2024-09-24 08:32 UTC, piofinn commented on packages/file-input/_file.scss
> +    color: var(--jkl-color-border-action);
Hvis denne blir brukt som tekstfarge er det nok bedre å bruke en av fargerollene for tekst 😊 F.eks. `var(--jkl-color-text-default)`.

2024-09-25 08:39 UTC, piofinn approved these changes

2024-09-25 08:53 UTC, merged