fix: feedback
fremtind/jokul pull request #4125
Opened 2024-09-25 10:15 UTC by ivarni

## 🎯 Sjekkliste

-   [ ] Nye features er dokumentert (sjekk [Contributing](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) om du er usikker på hva som trengs av dokumentasjon)
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [ ] `pnpm build` og `pnpm ci:test` gir ingen feil

2024-09-25 10:19 UTC, zenabii commented
https://github.com/fremtind/jokul/issues/3984

2024-09-25 10:45 UTC, piofinn requested changes

2024-09-25 10:45 UTC, piofinn commented on packages/menu-react/documentation/MenuToggleSwitchExample.tsx
> +import { Tooltip, TooltipContent, TooltipTrigger } from "../../tooltip-react/build";
Denne må fikses. Tror det riktigste blir

```suggestion
import { Tooltip, TooltipContent, TooltipTrigger } from "../../tooltip-react/src";
```

2024-09-30 07:28 UTC, piofinn requested changes

2024-09-30 07:28 UTC, piofinn commented on packages/contextual-menu-react/src/ContextualMenu.tsx
> +
Denne tomme linja må fjernes for at deprecation-meldingen skal bli med i de bygde filene

```suggestion
```

2024-09-30 07:29 UTC, kristianulv23 requested changes

2024-09-30 07:29 UTC, kristianulv23 commented on packages/contextual-menu-react/src/ContextualMenu.tsx
> + * Bruk heller komponenten `Menu` som er erstatning for ContextualMenu
Flisespikkeri: 

`som er en erstatning ...`

2024-09-30 07:29 UTC, kristianulv23 commented on packages/contextual-menu/contextual-menu.scss
> +/// Bruk heller komponenten `Menu` som er erstatning for ContextualMenu
Flisespikkeri: 

`som er en erstatning ...`

2024-09-30 20:18 UTC, zenabii commented
@kristianulv23 @piofinn siste sjekk? :D

2024-10-02 07:20 UTC, piofinn approved these changes

2024-10-02 08:56 UTC, ivarni commented
Trenger visst approve fra begge to her siden begge har requested changes

2024-10-02 12:49 UTC, kristianulv23 approved these changes

2024-10-02 20:37 UTC, merged