feat: felles stylesheet
fremtind/jokul pull request #4133
Opened 2024-10-01 07:48 UTC by zenabii

- Opprettet egen styles.scss som henter inn alle komponenter sine stylinger som per nå ligger i jokul > sec pakken vår. Dette må oppdateres manuelt for hver gang vi flytter komponenter inn i pakken
- Tanken er at med dette så kan teamene bestemme selv om de vil importere styles per komponent separat, eller kun forholde seg til én enkel import. 
- Vi må ta forbehold om at vi jobber med å få ned størrelsen i css filene, men per nå skal ikke filstørrelsen påvirke perfomance for noen.
- Har notert noen kommentarer hvor vi f.eks mangler index filer i komponentene sine styles mapper: kan jeg ta meg friheten til å rette opp dette i samme PR her? 😄 

Spørsmål:
- Må denne filen også eksporteres i index.ts under jokul > src? 
- Er det nok i build-styles.mjs at den hentes på samme måte som alle andre med kun denne builden på linje 13?         
`const sources = await glob("./src/**/[!_]*.scss", { ignore: "node_modules/**" }); `🤔

2024-10-01 07:51 UTC, ivarni commented on packages/jokul/src/styles/styles.scss
Jeg tror du må gi dem navn så de ikke krasjer, så
```
@use "../components/accordion/styles/index" as accordion;
```
osv.

Sånn jeg tolker byggfeilen i hvert fall

2024-10-01 07:55 UTC, piofinn commented on packages/jokul/src/styles/styles.scss
Jepp. Du kan også droppe `index` hvis du vil 😊 Det holder f.eks. med:

```scss
@use "../components/accordion/style" as accordion;
```

Det har jo ikke så mye å si, da :)

2024-10-01 07:57 UTC, piofinn commented
> * Må denne filen også eksporteres i index.ts under jokul > src?

Tror det aller beste er å legge inn en ny linje under `exports` i package.json som peker på denne fila.

> * Er det nok i build-styles.mjs at den hentes på samme måte som alle andre med kun denne builden på linje 13?
>   `const sources = await glob("./src/**/[!_]*.scss", { ignore: "node_modules/**" }); `🤔

Tror at den skal bli plukket opp av den glob-en ja!

2024-10-01 08:36 UTC, zenabii commented on packages/jokul/src/styles/styles.scss
ah nice, fikser :)

2024-10-02 06:37 UTC, ivarni commented
> Er det nok i build-styles.mjs at den hentes på samme måte som alle andre med kun denne builden på linje 13?
> const sources = await glob("./src/**/[!_]*.scss", { ignore: "node_modules/**" });

Jeg mener at fila ikke burde hete `_styles` men `styles` slik at bygget finner den. Da får også de som måtte finne å bruke CSS tilgang til én-import løsningen. Da skal det havne `.css` og `.min.css` filer på samme sted som den nye fila ligger og exporten i package-json bør være `"./styles": "./src/styles/*"`. 

Syns det er mer ryddig siden vi tilbyr CSS alle andre steder vi tilbyr SCSS.

2024-10-02 08:02 UTC, piofinn commented
> Jeg mener at fila ikke burde hete `_styles` men `styles` slik at bygget finner den.

Catcha ikke at den startet med understrek! Enig i at den bør bygges ut til CSS, ja :)

2024-10-02 10:06 UTC, ivarni requested changes
Er også noen imports som ikke virker pga manglende index-filer og et par moduler (table, toggle-switch) der index-fila har blitt feil (sannsynligvis under flyttingen).

Sånn sett veldig bra at vi nå har noe i bygg-pipeline som faktisk prøver å kompilere disse filene så vi kan fange opp sånne ting fremover :)

2024-10-02 10:06 UTC, ivarni commented on packages/jokul/package.json
> +        "./styles": "./src/styles/styles.scss",
```suggestion
        "./styles": "./src/styles/*",
```

2024-10-03 07:01 UTC, piofinn commented
> Er også noen imports som ikke virker pga manglende index-filer og et par moduler (table, toggle-switch) der index-fila har blitt feil (sannsynligvis under flyttingen).

Ser ut som feilen i `table` og `toggle-switch` er at selve stilarket ikke har blitt med i flyttingen til allpakka (sikkert fordi de ligger under `package.json` etc. i listen over filer). Så der skal det bare være å kopiere inn hhv. `table.scss` og `toggle-switch.scss` fra de respektive pakkene.

Ser også at `core.scss` ikke er med. Hvis vi vil at man skal kunne importere _kun_ dette stilarket må den også inn 😊

2024-10-07 05:29 UTC, ivarni commented
Jeg hijacker denne branchen og får bygget grønt siden Maria blir borte en liten stund

2024-10-07 06:18 UTC, ivarni approved these changes

2024-10-07 10:33 UTC, piofinn approved these changes

2024-10-07 10:41 UTC, merged