Gjør @fremtind/jokul kompatibel med Node 16 module resolution
fremtind/jokul pull request #4208
Opened 2024-10-23 15:02 UTC by piofinn

- Endrer `moduleResolution` til `NodeNext` i `@feemtind/jokul`
- Endrer alle `import`/`export` statements til å referere til filer med filendelse
- Oppretter separate typedefinisjoner for ESM og CJS ved bygg

**TODO:** Finne en god måte å endre filendelser fra `.js` til `.cjs` i typedefinisjonene for CJS. Uten dette funker ikke import vha `require()`. I terminalen funker `sed -i "s/\.js'/\.cjs'/g" build/cjs/**/*.d.cts`, men av en eller annen grunn funker dette ikke som en del av bygg-scriptet.

## 🎯 Sjekkliste

-   [ ] Nye features er dokumentert (sjekk [Contributing](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) om du er usikker på hva som trengs av dokumentasjon)
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [ ] `pnpm build` og `pnpm ci:test` gir ingen feil

2024-10-24 06:30 UTC, ivarni commented
> TODO: Finne en god måte å endre filendelser fra .js til .cjs i typedefinisjonene for CJS. Uten dette funker ikke import vha require(). I terminalen funker sed -i "s/\.js'/\.cjs'/g" build/cjs/**/*.d.cts, men av en eller annen grunn funker dette ikke som en del av bygg-scriptet.



![image](https://github.com/user-attachments/assets/7a878122-e56b-4c57-8689-af5512b06638)

2024-10-24 06:48 UTC, ivarni commented
https://github.com/fremtind/jokul/pull/4210/files

2024-10-24 07:03 UTC, piofinn commented
> https://github.com/fremtind/jokul/pull/4210/files

Nice! Så enkelt! Ser ut som jeg glemte å spesifisere rekursivitet et sted også, siden bygget feiler på "no such directory"

2024-10-24 07:05 UTC, ivarni commented
Jeg tror det var font-greiene mine, jeg laget en PR på å omstrukturere de så den mappa ligner mer på en komponent

2024-10-24 07:16 UTC, piofinn commented
> Jeg tror det var font-greiene mine, jeg laget en PR på å omstrukturere de så den mappa ligner mer på en komponent

Ja, jeg fant akkurat ut at det var den fila som klaget. Er litt skjørt det mønsteret for flytting av stilarkene 😅

2024-10-24 07:25 UTC, ivarni commented
Den gode nyheten med at det er skjørt er jo at vi ikke plutselig publisher noe som mangler masse greier vi trodde skulle været med :)

2024-10-24 10:34 UTC, piofinn commented
Ser ut som testene feiler for `@fremtind/jokul`-pakka fordi `moduleResolution` ikke er satt til `NodeNext` der testene kjører fra. Jest forstår altså ikke importene i testene inne i allpakka.

Siden Ivar foreslo at vi ikke vedlikeholder testene _utenfor_ allpakka (https://github.com/fremtind/jokul/pull/4211#discussion_r1814506240) foreslår jeg at jeg legger til Jest inne i allpakka med eget oppsett, og ber testene på rot om å ignorere `@fremtind/jokul`.

2024-10-25 03:40 UTC, ivarni commented on packages/jokul/package.json
> +        "refactor": "sed -i \"s/\\.js'/\\.cjs'/g\" build/cjs/**/*.d.cts",
```suggestion
```

2024-10-25 03:40 UTC, ivarni commented on packages/jokul/package.json
> +        "refactor": "sed -i \"s/\\.js'/\\.cjs'/g\" build/cjs/**/*.d.cts",
```suggestion
        "compile:scripts": "vite build --config vite.build.config.mjs"
```

2024-10-25 04:09 UTC, ivarni requested changes

2024-10-25 04:17 UTC, ivarni approved these changes

2024-10-25 04:18 UTC, ivarni commented
Fint å få fikset de småtingene men også fint å få denne diffen inn så det blir mindre krasj med andre oppgaver.

2024-10-25 06:42 UTC, kristianulv23 approved these changes

2024-10-25 07:03 UTC, piofinn commented on packages/jokul/vite.config.mjs
> Forøvrig skal vitest være smart nok til å skjønne at den skal gå i watch mode i dev og gjøre run i et CI miljø tror jeg?

Ooh, nice!

2024-10-25 07:05 UTC, piofinn commented
> Fint å få fikset de småtingene men også fint å få denne diffen inn så det blir mindre krasj med andre oppgaver.

Tror jeg drar det inn nå og lager en egen PR med de to forslagene dine!

2024-10-25 07:15 UTC, merged