feat: add CheckboxPanel and move RadioPanel
fremtind/jokul pull request #4245
Opened 2024-10-31 07:57 UTC by ivarni

ISSUES CLOSED: #4108

## 🎯 Sjekkliste

-   [x] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [x] `pnpm build` og `pnpm ci:test` gir ingen feil

2024-10-31 12:01 UTC, piofinn requested changes
Ser ut som `exports`-feltet må endres. Har også et innspill om typer for Props i de to komponentene.

2024-10-31 12:18 UTC, ivarni commented on packages/jokul/package.json
> +                "default": "./build/es/components/checkbox-panel/index.js",
Argh, ja den glemte jeg

2024-10-31 12:19 UTC, ivarni commented on packages/jokul/src/components/input-panel/RadioPanel.tsx
> +};
RadioPanel vil ikke fungere skikkelig sammen med RadioPanelGroup dersom den ikke har en value så derfor ønsker jeg at value er required.

2024-10-31 12:21 UTC, piofinn commented on packages/jokul/src/components/input-panel/RadioPanel.tsx
> +};
Hehe, denne ble litt kryptisk alene. Jeg skrev det samme i CheckboxPanel, men ser ikke ut som jeg faktisk kommenterte 😑 Lurte i hvert fall på om vi burde basere oss på typene fra `BasePanel` i de to andre komponentene, i stedet for å basere oss direkte på `input`-attributtene.

2024-10-31 12:28 UTC, ivarni commented on packages/jokul/src/components/input-panel/RadioPanel.tsx
> +};
Jeg vet ikke om jeg syns det er noe godt pattern egentlig. Dette er jo en input, om noe enhanced. Det er vanskelig å forutset alt det vil være relevant å kunne sende inn til en input. Den base-greia er først og fremst en mekanisme for å være litt DRY.

2024-10-31 12:44 UTC, ivarni commented on packages/jokul/src/components/input-panel/RadioPanel.tsx
> +};
I tillegg tar jo også Base-komponenten inn ting som er internt og ikke en del av public APIet til de to andre så da må det lukes ut med `Omit`.

2024-11-01 09:35 UTC, piofinn approved these changes

2024-11-01 12:27 UTC, merged