docs: add contributing-file for mono package
fremtind/jokul pull request #4265
Opened 2024-11-07 11:21 UTC by ivarni

2024-11-07 16:19 UTC, piofinn requested changes

2024-11-07 16:19 UTC, piofinn commented on packages/jokul/CONTRIBUTING.md
> +                "types": "./build/es/components/[navn]/index.d.ts"
```suggestion
                "types": "./build/es/components/[navn]/index.d.ts"
                "default": "./build/es/components/[navn]/index.js",
```

2024-11-07 16:19 UTC, piofinn commented on packages/jokul/CONTRIBUTING.md
> +                "types": "./build/cjs/components/[navn]/index.d.cts"
```suggestion
                "types": "./build/cjs/components/[navn]/index.d.cts"
                "default": "./build/cjs/components/[navn]/index.cjs",
```

2024-11-08 05:50 UTC, ivarni commented on packages/jokul/CONTRIBUTING.md
> +                "types": "./build/es/components/[navn]/index.d.ts"
Right, vi bytta om på de ja

2024-11-08 08:36 UTC, kristianulv23 approved these changes

2024-11-08 08:59 UTC, piofinn approved these changes

2024-11-08 09:04 UTC, merged