Feat/chips
fremtind/jokul pull request #4271
Opened 2024-11-08 12:45 UTC by Chrihenn

## 🎯 Sjekkliste

-   [ ] Nye features er dokumentert (sjekk [Contributing](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) om du er usikker på hva som trengs av dokumentasjon)
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [ ] `pnpm build` og `pnpm ci:test` gir ingen feil

2024-11-08 14:01 UTC, kennidenni submitted a review, later dismissed

2024-11-08 14:01 UTC, kennidenni commented on packages/jokul/package.json
> +                "default": "./build/es/components/chip/index.js",
Default må være under

2024-11-08 14:01 UTC, kennidenni commented on packages/jokul/package.json
> +                "default": "./build/cjs/components/chip/index.cjs",
default må være under

2024-11-13 07:34 UTC, ivarni requested changes

2024-11-13 07:34 UTC, ivarni commented on packages/chip-react/integration/chip.spec.js
Denne gjør ingen skade men heller ingen nytte siden vi disablet cypress-testene for over ett år siden :)

2024-11-13 07:34 UTC, ivarni commented on packages/chip-react/src/Chip.tsx
> +import clsx from "clsx";
```suggestion
import clsx from "classnames";
```

2024-11-13 07:34 UTC, ivarni commented on packages/chip-react/src/Chip.tsx
> +import clsx from "clsx";
I de gamle pakkene har vi brukt `classnames` og ikke `clsx`, noe som betyr at alle som bruker de gamle pakkene allerede har `classnames` installert. Da er det like greit at vi ikke drar inn `clsx` i tillegg.

2024-11-13 07:34 UTC, ivarni commented on packages/chip-react/package.json
> +        "clsx": "^2.1.1"
```suggestion
```

2024-11-13 07:34 UTC, ivarni commented on packages/chip-react/package.json
> +        "clsx": "^2.1.1"
Hvis vi bruker `classnames` slik de andre _jkl-*_ pakkene allerede gjør slipper applikasjonene og installere enda en pakke som gjør akkurat det samme.

2024-11-13 07:34 UTC, ivarni commented on packages/chip/_index.scss
> +@use "@fremtind/jkl-icon-button" as icon-button;
Hvorfor trenger vi icon-button her?

2024-11-13 07:34 UTC, ivarni commented on packages/chip/chip.scss
> +
Disse er `@deprecated`, bruk heller _"jkl.compact-density"_ mixinen inni `.jkl-chip`.

2024-11-13 07:34 UTC, ivarni commented on packages/chip/chip.scss
> +
https://github.com/fremtind/jokul/blob/main/packages/jokul/src/core/jkl/_theme.scss#L39-L108

2024-11-13 07:34 UTC, ivarni commented on packages/jokul/src/components/chip/documentation/Chip.mdx
Så lenge vi ikke bruke `.mdx` filer til noe i jokul-pakka tenker jeg det er bedre å ikke ha dem liggende her. Det er bedre å vedlikeholde dem på ett sted (i chip-react pakka der den brukes feks) og så kopiere de over når har funnet ut hvordan de skal brukes.

2024-11-13 07:34 UTC, ivarni commented on packages/jokul/src/components/chip/documentation/ChipExample.tsx
> +};
```suggestion
```

2024-11-13 07:34 UTC, ivarni commented on packages/jokul/src/components/chip/documentation/ChipExample.tsx
> +};
Dette brukes pr i dag ikke til noe i jokul-pakka.

2024-11-13 12:55 UTC, piofinn requested changes
Ser bra ut! Komponenten har vel fortsatt strengt tatt feil høyde/størrelse på grunn av border, men tenker vi heller kan fikse det når den er ute.

Jeg tror kanskje det hadde vært fint å rydde litt i commit-historikken også. Her kan man kanskje bare squashe til én enkelt commit `feat: legg til ny komponent Chip`?

2024-11-13 12:55 UTC, piofinn commented on packages/chip/chip.scss
> +    }
Vet at Ivar akkurat ba deg om å flytte disse 😅 Men hvis de skal brukes inni klassen må de flyttes ned til linje 46 (før forced-colors-mixinen) eller senere for ikke å få deprecation warnings fra Sass under bygg.

Enda bedre: Jeg har nå fikset bug-en vi fant under Jøkuluka, så du kan nå bruke de nye mixin-ene i toppen av fila (der du hadde de gamle) med klassenavn for scoping 🎉 Altså:

```scss
@include jkl.compact-density(".jkl-chip") {
    /* Variabler her… */
}
```

2024-11-13 12:55 UTC, piofinn commented on packages/chip-react/src/Chip.tsx
> +            data-size={size}
Dette er litt flisespikking, men jeg tror jeg ville foretrukket denne som en variant via klassenavn, og holde av `data`-attributter til state som endrer seg under bruk.

2024-11-13 12:55 UTC, piofinn commented on packages/chip-react/src/Chip.tsx
> +            data-density={density}
Som vi diskuterte i chatten kan denne godt fjernes helt (inkludert prop-en `density`).
```suggestion
```

2024-11-13 13:37 UTC, piofinn commented
> > Ser bra ut! Komponenten har vel fortsatt strengt tatt feil høyde/størrelse på grunn av border, men tenker vi heller kan fikse det når den er ute.
> > Jeg tror kanskje det hadde vært fint å rydde litt i commit-historikken også. Her kan man kanskje bare squashe til én enkelt commit `feat: legg til ny komponent Chip`?
> > **Edit**: Merket som changes requested mest så den ikke ble automerget før det var tatt stilling til kommentarene
> 
> Det har jeg løst ved å bruke inset box-shadow fremfor border.

Ah! Det skrev vi oss nettopp bort fra i mange komponenter ettersom det ikke er så bra for tilgjengelighet 😅 Hvis brukeren har på `prefers-contrast: more` eller `forced-colors: active` vil ikke box-shadows vises i det hele tatt.

2024-11-13 13:40 UTC, kristianulv23 commented
> > > Ser bra ut! Komponenten har vel fortsatt strengt tatt feil høyde/størrelse på grunn av border, men tenker vi heller kan fikse det når den er ute.
> > > Jeg tror kanskje det hadde vært fint å rydde litt i commit-historikken også. Her kan man kanskje bare squashe til én enkelt commit `feat: legg til ny komponent Chip`?
> > > **Edit**: Merket som changes requested mest så den ikke ble automerget før det var tatt stilling til kommentarene
> > 
> > 
> > Det har jeg løst ved å bruke inset box-shadow fremfor border.
> 
> Ah! Det skrev vi oss nettopp bort fra i mange komponenter ettersom det ikke er så bra for tilgjengelighet 😅 Hvis brukeren har på `prefers-contrast: more` eller `forced-colors: active` vil ikke box-shadows vises i det hele tatt.

Og jeg som trodde jeg var smart. Så feil kan man ta😋

2024-11-13 13:51 UTC, kristianulv23 commented
> > > Ser bra ut! Komponenten har vel fortsatt strengt tatt feil høyde/størrelse på grunn av border, men tenker vi heller kan fikse det når den er ute.
> > > Jeg tror kanskje det hadde vært fint å rydde litt i commit-historikken også. Her kan man kanskje bare squashe til én enkelt commit `feat: legg til ny komponent Chip`?
> > > **Edit**: Merket som changes requested mest så den ikke ble automerget før det var tatt stilling til kommentarene
> > 
> > 
> > Det har jeg løst ved å bruke inset box-shadow fremfor border.
> 
> Ah! Det skrev vi oss nettopp bort fra i mange komponenter ettersom det ikke er så bra for tilgjengelighet 😅 Hvis brukeren har på `prefers-contrast: more` eller `forced-colors: active` vil ikke box-shadows vises i det hele tatt.

Hva med å ha border som en fallback?

`@media (prefers-contrast: more), (forced-colors: active) {
   ...
}`

2024-11-13 14:28 UTC, piofinn commented
> Hva med å ha border som en fallback?
> 
> `@media (prefers-contrast: more), (forced-colors: active) { ... }`

I så fall burde vi nok heller ha den omvendt, og sjekke for `prefers-contrast: no-preference` og `forced-colors: none` før vi bruker en box-shadow. Men jeg tror uansett jeg foretrekker å finne en løsning som ikke krever fallbacks; de kan fort være vanskelige å forstå hvis man ikke har kontekst (a.k.a. om noen måneder 😅).

Snakka med Jonas før jeg ble ferdig med å skrive kommentar 😆 Vi har endra komponenten i Figma til å bruke fast høyde basert på en variabel, så vi kan gjøre det slik i komponenten også!

![Skjermbilde 2024-11-13 kl  15 28 20](https://github.com/user-attachments/assets/d547c339-a04c-46ca-b8a5-e0cd26a032cb)

2024-11-13 14:39 UTC, ivarni commented on packages/jokul/src/components/chip/Chip.tsx
> +import { CloseIcon } from "../icon/index.js";
```suggestion
import { CloseIcon } from "../icon/icons/CloseIcon.js";
```

2024-11-13 14:41 UTC, ivarni commented on packages/jokul/src/components/chip/Chip.tsx
> +import { CloseIcon } from "../icon/index.js";
Så nettopp at jeg hadde syndet mot dette i Expandable komponenten så tenkte å sjekke om jeg var alene :)

2024-11-13 15:28 UTC, piofinn approved these changes
Ser bra ut! 🎉

Variablene for block-padding er streng tatt ikke nødvendige lenger, men gjør ingenting at de er der enn så lenge, så er good to go fra min side! 😄

2024-11-13 15:30 UTC, kristianulv23 commented
> Ser bra ut! 🎉
> 
> Variablene for block-padding er streng tatt ikke nødvendige lenger, men gjør ingenting at de er der enn så lenge, så er good to go fra min side! 😄

Ja la merke til det så jeg fikk fjernet de isted😄

2024-11-14 05:55 UTC, ivarni approved these changes

2024-11-14 06:06 UTC, merged