WIP: Ny expandable
fremtind/jokul pull request #4284
Opened 2024-11-12 07:51 UTC by ivarni

TODO:

- [ ] Sjekk at man kan lage custom widgets med aria og Expander komponenten (mekk et eksempel med '<div>' og '<button>' i stedet for '<details>' og '<summary>')
- [ ] Sjekk at ekspanderende table-rows fungerer og ser bra ut
- [ ] Animering av åpning og lukking
- [ ] Accordion bør deprecates
- [ ] Dokumentasjon (vi har ikke noe sted å legge det, så kanskje vi må vente litt med det?)
- [ ] Figmating må være på plass

2024-11-21 15:12 UTC, piofinn requested changes
Noen småting jeg har lyst til å endre, men dette ser veldig bra ut!

2024-11-21 15:12 UTC, piofinn commented on packages/expandable/expandable.scss
> +    }
Synes ikke vi bør sette marginer utenfor komponentene våre. Ser at dette nok er riktig i de fleste tilfeller, men det vil f.eks. bli visuelt feil hvis man fordeler `Expandable`-komponenter i et grid, eller i en flex-layout som wrapper vertikalt.

```suggestion
```

2024-11-22 11:37 UTC, ivarni commented on packages/expandable-react/src/Expandable.tsx
Hm.. husker ikke hvorfor jeg gjorde det, lurer på om vurderingen ble tatt før jeg flyttet ut de to andre komponentene til egne filer 👍🏽

2024-11-22 11:52 UTC, ivarni commented on packages/expandable-react/src/Expandable.tsx
> +                }
det skapte ingen problemer i noen av de browserene jeg testet det i, hverken warnings eller rare attributes, det var derfor jeg beholdt det der, men kan godt hive på en sjekk.

2024-11-22 12:06 UTC, ivarni commented on packages/expandable/expandable.scss
> +            border-radius: var(--border-radius);
Det at den er wrappet i `.jkl-expandable` her er for å unngå dette problemet:

<img width="300" alt="image" src="https://github.com/user-attachments/assets/d2b0b9a0-8134-406f-9a06-71e290e11bea">

De har valgt seg en farge for hover som ikke er den semantisk riktige så det krasjet med tabell-rader som faktisk bruker hover-fargen. Derfor har `Expander` bare en hover effect dersom den er inni en `ExpandablePanel`. Ikke den mest optimale løsningen men man kan fort tenke seg at denne effekten kunne skapt problemer når knappen brukes alene i andre kontekster også.

Det med border-radius'en la vi ikke merke til men nå når du sier det så ser det ganske kjipt ut 😬 , ser om jeg finner en fiks på det.

2024-11-22 12:19 UTC, ivarni commented on packages/expandable/expandable.scss
> +            border-radius: var(--border-radius);
hah! `overflow: clip` på `details` elementet :D

2024-11-22 13:00 UTC, ivarni commented on packages/expandable/expandable.scss
> +            border-radius: var(--border-radius);
Det var bare å bruke overflow:hidden på details så vil ikke bakgrunnen til summary stikke ut noe steder. 

Jeg tror ikke det at det ser ut som høyden endrer seg har noe med dette å gjøre.

2024-11-22 13:10 UTC, ivarni commented on packages/expandable/expandable.scss
> +            border-radius: var(--border-radius);
Det er fordi det ikke er noen border der når den er åpen... hvis jeg gjør `<summary>` 1px høyere i open-state så ser det mye smoothere ut.

2024-11-22 13:22 UTC, ivarni commented on packages/expandable/expandable.scss
> +            border-radius: var(--border-radius);
Jeg la på en transparent 1px høy border under `<summar>` når `<details>` er åpen og det hjalp veldig på opplevelsen når den åpnes og lukkes.

2024-11-25 12:09 UTC, Stormoen commented on packages/expandable/expandable.scss
> +            border-radius: var(--border-radius);
Ser at det mangler bold tittel i åpen tilstand.
Hvilken variabel er brukt på hover? Synes den har så mye kontrast i dark. 
I Figma juksa jeg litt - vi kan ta en prat om det på kontoet i morra.

2024-11-25 12:32 UTC, ivarni commented on packages/expandable/expandable.scss
> +            border-radius: var(--border-radius);
La ikke merke til at det var bold i hover, kan få det på plass.

hover bakgrunn er _background-interactive-selected_ som vi snakket om

2024-11-27 14:49 UTC, Stormoen approved these changes

2024-11-28 09:42 UTC, piofinn approved these changes

2024-11-28 09:54 UTC, merged