Refaktorer Tag-komponenten og oppdater Combobox til å bruke Chip
fremtind/jokul pull request #4291
Opened 2024-11-13 07:01 UTC by kristianulv23

Fjerner dismissable-funksjonaliteten for Tag-komponenten, da dette nå dekkes av den nye Chip-komponenten. Oppdaterer samtidig Combobox-komponenten til å bruke Chip i stedet for Tag.

- Closes #4286
- Closes #4288 

## 🎯 Sjekkliste

-   [ ] Nye features er dokumentert (sjekk [Contributing](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md) om du er usikker på hva som trengs av dokumentasjon)
-   [ ] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [ ] `pnpm build` og `pnpm ci:test` gir ingen feil

2024-11-15 10:33 UTC, ivarni requested changes
Jeg testet litt med VoiceOver og dette er muligens ikke nytt men det var litt klønete å gjøre valg siden focus hoppet tilbake til input-feltet hver gang jeg valgte noe fra lista. Kanskje det er sånn det alltid har vært.

Det jeg syns vi må gjøre er å gi en bedre label til "fjern valg" knappen, dvs chippen. Det er ingen hint å få om hva som skjer når man trykker på den. Vi burde si at det å trykke vil fjerne valget.

2024-11-15 10:33 UTC, ivarni commented on packages/chip-react/src/Chip.tsx
> +Chip.displayName = "Chip";
Tror ikke dette trengs når du bruker en named function i `forwardRef`? Litt usikker, kan jo eventuelt teste med å kaste en exception inn komponenten og se om navnet dukker opp i stacktracen.

2024-11-18 10:44 UTC, kristianulv23 commented
> Jeg testet litt med VoiceOver og dette er muligens ikke nytt men det var litt klønete å gjøre valg siden focus hoppet tilbake til input-feltet hver gang jeg valgte noe fra lista. Kanskje det er sånn det alltid har vært.
> 
> Det jeg syns vi må gjøre er å gi en bedre label til "fjern valg" knappen, dvs chippen. Det er ingen hint å få om hva som skjer når man trykker på den. Vi burde si at det å trykke vil fjerne valget.

Jeg oppretter et issue for dette og jobber med en løsning i en egen branch #4298

2024-11-20 09:08 UTC, ivarni approved these changes

2024-11-20 09:22 UTC, merged